import type {
  Ejercicio,
  SustitucionEjercicio,
  ClienteEntrenamiento,
  SemanaEntrenamiento,
  SesionEntrenamiento,
  TrainerStats,
  GrupoMuscular,
  TipoMaterial,
  NivelDificultad,
  TipoPlantilla,
  TipoLesion,
  TipoRestriccion,
} from "./schema";

// ============================================
// BIBLIOTECA DE EJERCICIOS
// ============================================

export const ejerciciosData: Ejercicio[] = [
  // PECHO
  {
    id: "ej-001",
    nombre: "Press de banca con barra",
    nombreIngles: "Barbell Bench Press",
    descripcion: "Ejercicio principal para el desarrollo del pectoral mayor",
    grupoMuscular: "pecho",
    gruposSecundarios: ["triceps", "hombros"],
    material: ["barra"],
    nivel: "intermedio",
    videoUrl: "https://www.youtube.com/embed/rT7DgCr-3pg",
    thumbnailUrl: "/ejercicios/bench-press.jpg",
    instrucciones: [
      "Acuéstate en el banco con los pies apoyados en el suelo",
      "Agarra la barra con un agarre ligeramente más ancho que los hombros",
      "Baja la barra de forma controlada hasta el pecho",
      "Empuja la barra hacia arriba hasta extender los brazos",
    ],
    erroresComunes: ["Rebotar la barra en el pecho", "Arquear excesivamente la espalda", "No controlar la bajada"],
    sustituciones: ["ej-002", "ej-003"],
    etiquetas: ["compuesto", "fuerza", "principal"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-002",
    nombre: "Press de banca con mancuernas",
    nombreIngles: "Dumbbell Bench Press",
    descripcion: "Variante con mayor rango de movimiento",
    grupoMuscular: "pecho",
    gruposSecundarios: ["triceps", "hombros"],
    material: ["mancuernas"],
    nivel: "principiante",
    videoUrl: "https://www.youtube.com/embed/VmB1G1K7v94",
    instrucciones: [
      "Siéntate en el banco con una mancuerna en cada mano",
      "Acuéstate llevando las mancuernas al pecho",
      "Presiona hacia arriba hasta extender los brazos",
      "Baja de forma controlada",
    ],
    sustituciones: ["ej-001", "ej-003"],
    etiquetas: ["compuesto", "fuerza"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-003",
    nombre: "Flexiones",
    nombreIngles: "Push-ups",
    descripcion: "Ejercicio de peso corporal para pecho y tríceps",
    grupoMuscular: "pecho",
    gruposSecundarios: ["triceps", "hombros", "core"],
    material: ["peso_corporal"],
    nivel: "principiante",
    videoUrl: "https://www.youtube.com/embed/IODxDxX7oi4",
    sustituciones: ["ej-001", "ej-002"],
    etiquetas: ["peso_corporal", "básico"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-004",
    nombre: "Aperturas con mancuernas",
    nombreIngles: "Dumbbell Flyes",
    grupoMuscular: "pecho",
    material: ["mancuernas"],
    nivel: "principiante",
    videoUrl: "https://www.youtube.com/embed/eozdVDA78K0",
    sustituciones: ["ej-005"],
    etiquetas: ["aislamiento", "accesorio"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-005",
    nombre: "Cruces en polea",
    nombreIngles: "Cable Crossover",
    grupoMuscular: "pecho",
    material: ["poleas"],
    nivel: "intermedio",
    videoUrl: "https://www.youtube.com/embed/taI4XduLpTk",
    sustituciones: ["ej-004"],
    etiquetas: ["aislamiento", "accesorio"],
    activo: true,
    createdAt: "2024-01-01",
  },
  // ESPALDA
  {
    id: "ej-006",
    nombre: "Dominadas",
    nombreIngles: "Pull-ups",
    descripcion: "Ejercicio principal para el desarrollo del dorsal",
    grupoMuscular: "espalda",
    gruposSecundarios: ["biceps", "antebrazos"],
    material: ["peso_corporal"],
    nivel: "intermedio",
    videoUrl: "https://www.youtube.com/embed/eGo4IYlbE5g",
    sustituciones: ["ej-007", "ej-008"],
    etiquetas: ["compuesto", "fuerza", "principal"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-007",
    nombre: "Jalón al pecho",
    nombreIngles: "Lat Pulldown",
    grupoMuscular: "espalda",
    gruposSecundarios: ["biceps"],
    material: ["poleas", "maquina"],
    nivel: "principiante",
    videoUrl: "https://www.youtube.com/embed/CAwf7n6Luuc",
    sustituciones: ["ej-006"],
    etiquetas: ["compuesto", "accesorio"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-008",
    nombre: "Remo con barra",
    nombreIngles: "Barbell Row",
    grupoMuscular: "espalda",
    gruposSecundarios: ["biceps", "core"],
    material: ["barra"],
    nivel: "intermedio",
    videoUrl: "https://www.youtube.com/embed/FWJR5Ve8bnQ",
    sustituciones: ["ej-009"],
    etiquetas: ["compuesto", "fuerza", "principal"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-009",
    nombre: "Remo con mancuerna",
    nombreIngles: "Dumbbell Row",
    grupoMuscular: "espalda",
    gruposSecundarios: ["biceps"],
    material: ["mancuernas"],
    nivel: "principiante",
    videoUrl: "https://www.youtube.com/embed/pYcpY20QaE8",
    sustituciones: ["ej-008"],
    etiquetas: ["compuesto", "accesorio"],
    activo: true,
    createdAt: "2024-01-01",
  },
  // PIERNAS
  {
    id: "ej-010",
    nombre: "Sentadilla con barra",
    nombreIngles: "Barbell Squat",
    descripcion: "El rey de los ejercicios de pierna",
    grupoMuscular: "cuadriceps",
    gruposSecundarios: ["gluteos", "isquiotibiales", "core"],
    material: ["barra"],
    nivel: "intermedio",
    videoUrl: "https://www.youtube.com/embed/ultWZbUMPL8",
    sustituciones: ["ej-011", "ej-012"],
    etiquetas: ["compuesto", "fuerza", "principal"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-011",
    nombre: "Sentadilla goblet",
    nombreIngles: "Goblet Squat",
    grupoMuscular: "cuadriceps",
    gruposSecundarios: ["gluteos", "core"],
    material: ["mancuernas", "kettlebell"],
    nivel: "principiante",
    videoUrl: "https://www.youtube.com/embed/MeIiIdhvXT4",
    sustituciones: ["ej-010"],
    etiquetas: ["compuesto", "básico"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-012",
    nombre: "Prensa de piernas",
    nombreIngles: "Leg Press",
    grupoMuscular: "cuadriceps",
    gruposSecundarios: ["gluteos"],
    material: ["maquina"],
    nivel: "principiante",
    videoUrl: "https://www.youtube.com/embed/IZxyjW7MPJQ",
    sustituciones: ["ej-010", "ej-011"],
    etiquetas: ["compuesto", "accesorio"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-013",
    nombre: "Peso muerto rumano",
    nombreIngles: "Romanian Deadlift",
    grupoMuscular: "isquiotibiales",
    gruposSecundarios: ["gluteos", "espalda"],
    material: ["barra", "mancuernas"],
    nivel: "intermedio",
    videoUrl: "https://www.youtube.com/embed/JCXUYuzwNrM",
    sustituciones: ["ej-014"],
    etiquetas: ["compuesto", "fuerza"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-014",
    nombre: "Curl femoral",
    nombreIngles: "Leg Curl",
    grupoMuscular: "isquiotibiales",
    material: ["maquina"],
    nivel: "principiante",
    videoUrl: "https://www.youtube.com/embed/1Tq3QdYUuHs",
    sustituciones: ["ej-013"],
    etiquetas: ["aislamiento", "accesorio"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-015",
    nombre: "Hip Thrust",
    nombreIngles: "Hip Thrust",
    grupoMuscular: "gluteos",
    gruposSecundarios: ["isquiotibiales"],
    material: ["barra"],
    nivel: "intermedio",
    videoUrl: "https://www.youtube.com/embed/SEdqd1n0cvg",
    etiquetas: ["compuesto", "principal"],
    activo: true,
    createdAt: "2024-01-01",
  },
  // HOMBROS
  {
    id: "ej-016",
    nombre: "Press militar con barra",
    nombreIngles: "Overhead Press",
    grupoMuscular: "hombros",
    gruposSecundarios: ["triceps", "core"],
    material: ["barra"],
    nivel: "intermedio",
    videoUrl: "https://www.youtube.com/embed/2yjwXTZQDDI",
    sustituciones: ["ej-017"],
    etiquetas: ["compuesto", "fuerza", "principal"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-017",
    nombre: "Press de hombros con mancuernas",
    nombreIngles: "Dumbbell Shoulder Press",
    grupoMuscular: "hombros",
    gruposSecundarios: ["triceps"],
    material: ["mancuernas"],
    nivel: "principiante",
    videoUrl: "https://www.youtube.com/embed/qEwKCR5JCog",
    sustituciones: ["ej-016"],
    etiquetas: ["compuesto", "accesorio"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-018",
    nombre: "Elevaciones laterales",
    nombreIngles: "Lateral Raises",
    grupoMuscular: "hombros",
    material: ["mancuernas"],
    nivel: "principiante",
    videoUrl: "https://www.youtube.com/embed/3VcKaXpzqRo",
    etiquetas: ["aislamiento", "accesorio"],
    activo: true,
    createdAt: "2024-01-01",
  },
  // BRAZOS
  {
    id: "ej-019",
    nombre: "Curl de bíceps con barra",
    nombreIngles: "Barbell Curl",
    grupoMuscular: "biceps",
    material: ["barra"],
    nivel: "principiante",
    videoUrl: "https://www.youtube.com/embed/kwG2ipFRgfo",
    sustituciones: ["ej-020"],
    etiquetas: ["aislamiento", "accesorio"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-020",
    nombre: "Curl de bíceps con mancuernas",
    nombreIngles: "Dumbbell Curl",
    grupoMuscular: "biceps",
    material: ["mancuernas"],
    nivel: "principiante",
    videoUrl: "https://www.youtube.com/embed/ykJmrZ5v0Oo",
    sustituciones: ["ej-019"],
    etiquetas: ["aislamiento", "accesorio"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-021",
    nombre: "Extensión de tríceps en polea",
    nombreIngles: "Tricep Pushdown",
    grupoMuscular: "triceps",
    material: ["poleas"],
    nivel: "principiante",
    videoUrl: "https://www.youtube.com/embed/2-LAMcpzODU",
    sustituciones: ["ej-022"],
    etiquetas: ["aislamiento", "accesorio"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-022",
    nombre: "Fondos en paralelas",
    nombreIngles: "Dips",
    grupoMuscular: "triceps",
    gruposSecundarios: ["pecho", "hombros"],
    material: ["peso_corporal"],
    nivel: "intermedio",
    videoUrl: "https://www.youtube.com/embed/2z8JmcrW-As",
    sustituciones: ["ej-021"],
    etiquetas: ["compuesto", "peso_corporal"],
    activo: true,
    createdAt: "2024-01-01",
  },
  // CORE
  {
    id: "ej-023",
    nombre: "Plancha",
    nombreIngles: "Plank",
    grupoMuscular: "core",
    material: ["peso_corporal"],
    nivel: "principiante",
    videoUrl: "https://www.youtube.com/embed/ASdvN_XEl_c",
    etiquetas: ["isométrico", "básico"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-024",
    nombre: "Ab Wheel Rollout",
    nombreIngles: "Ab Wheel Rollout",
    grupoMuscular: "core",
    material: ["sin_material"],
    nivel: "intermedio",
    videoUrl: "https://www.youtube.com/embed/rqiTPdK1c_I",
    etiquetas: ["dinamico", "avanzado"],
    activo: true,
    createdAt: "2024-01-01",
  },
];

// ============================================
// SUSTITUCIONES DE EJERCICIOS
// ============================================

export const sustitucionesData: SustitucionEjercicio[] = [
  {
    ejercicioOriginalId: "ej-001",
    ejercicioSustitutoId: "ej-002",
    ejercicioSustitutoNombre: "Press de banca con mancuernas",
    razon: "material",
    equivalencia: 90,
    notas: "Mayor rango de movimiento, menos peso total",
  },
  {
    ejercicioOriginalId: "ej-001",
    ejercicioSustitutoId: "ej-003",
    ejercicioSustitutoNombre: "Flexiones",
    razon: "material",
    equivalencia: 70,
    notas: "Sin equipamiento, ajustar volumen",
  },
  {
    ejercicioOriginalId: "ej-010",
    ejercicioSustitutoId: "ej-012",
    ejercicioSustitutoNombre: "Prensa de piernas",
    razon: "lesion",
    equivalencia: 75,
    notas: "Para problemas lumbares, menor demanda de core",
  },
  {
    ejercicioOriginalId: "ej-016",
    ejercicioSustitutoId: "ej-017",
    ejercicioSustitutoNombre: "Press de hombros con mancuernas",
    razon: "lesion",
    equivalencia: 85,
    notas: "Mejor para problemas de hombro, permite rotación natural",
  },
];

// ============================================
// CLIENTES DE ENTRENAMIENTO
// ============================================

export const clientesEntrenamientoData: ClienteEntrenamiento[] = [
  {
    id: "cli-001",
    nombre: "María García López",
    email: "maria.garcia@email.com",
    avatar: "/avatars/arhamkhnz.png",
    lesiones: [],
    restricciones: [],
    plantillaActual: "torso_pierna",
    adherencia: {
      clienteId: "cli-001",
      periodo: "semana",
      sesionesCompletadas: 4,
      sesionesPlanificadas: 4,
      porcentajeSesiones: 100,
      seriesHechas: 64,
      seriesPlanificadas: 68,
      porcentajeSeries: 94,
      volumenSemanal: 12500,
      rpeMedio: 7.5,
      tendencia: "estable",
    },
  },
  {
    id: "cli-002",
    nombre: "Carlos Rodríguez Pérez",
    email: "carlos.rodriguez@email.com",
    lesiones: ["lumbar"],
    restricciones: ["sin_peso_libre"],
    restriccionesCustom: ["Evitar cargas axiales pesadas"],
    plantillaActual: "full_body",
    adherencia: {
      clienteId: "cli-002",
      periodo: "semana",
      sesionesCompletadas: 2,
      sesionesPlanificadas: 3,
      porcentajeSesiones: 67,
      seriesHechas: 38,
      seriesPlanificadas: 54,
      porcentajeSeries: 70,
      volumenSemanal: 8200,
      rpeMedio: 6.8,
      tendencia: "bajando",
    },
  },
  {
    id: "cli-003",
    nombre: "Ana Martínez Sánchez",
    email: "ana.martinez@email.com",
    lesiones: ["hombro"],
    restricciones: ["sin_press_vertical", "sin_rotacion_externa"],
    plantillaActual: "ppl",
    adherencia: {
      clienteId: "cli-003",
      periodo: "semana",
      sesionesCompletadas: 5,
      sesionesPlanificadas: 6,
      porcentajeSesiones: 83,
      seriesHechas: 72,
      seriesPlanificadas: 80,
      porcentajeSeries: 90,
      volumenSemanal: 15800,
      rpeMedio: 7.2,
      tendencia: "subiendo",
    },
  },
  {
    id: "cli-004",
    nombre: "Pedro López Fernández",
    email: "pedro.lopez@email.com",
    lesiones: ["rodilla"],
    restricciones: ["sin_flexion_rodilla", "sin_impacto"],
    plantillaActual: "upper_lower",
    adherencia: {
      clienteId: "cli-004",
      periodo: "semana",
      sesionesCompletadas: 4,
      sesionesPlanificadas: 4,
      porcentajeSesiones: 100,
      seriesHechas: 56,
      seriesPlanificadas: 60,
      porcentajeSeries: 93,
      volumenSemanal: 11200,
      rpeMedio: 7.8,
      tendencia: "estable",
    },
  },
  {
    id: "cli-005",
    nombre: "Laura Sánchez Gil",
    email: "laura.sanchez@email.com",
    lesiones: [],
    restricciones: ["solo_mancuernas"],
    restriccionesCustom: ["Entrena en casa"],
    plantillaActual: "full_body",
    adherencia: {
      clienteId: "cli-005",
      periodo: "semana",
      sesionesCompletadas: 3,
      sesionesPlanificadas: 3,
      porcentajeSesiones: 100,
      seriesHechas: 45,
      seriesPlanificadas: 45,
      porcentajeSeries: 100,
      volumenSemanal: 9500,
      rpeMedio: 8.1,
      tendencia: "subiendo",
    },
  },
  {
    id: "cli-006",
    nombre: "Javier Ruiz Torres",
    email: "javier.ruiz@email.com",
    lesiones: ["cervical", "hombro"],
    restricciones: ["sin_barra", "rango_limitado"],
    plantillaActual: "torso_pierna",
    adherencia: {
      clienteId: "cli-006",
      periodo: "semana",
      sesionesCompletadas: 3,
      sesionesPlanificadas: 4,
      porcentajeSesiones: 75,
      seriesHechas: 48,
      seriesPlanificadas: 64,
      porcentajeSeries: 75,
      volumenSemanal: 7800,
      rpeMedio: 6.5,
      tendencia: "bajando",
    },
  },
];

// ============================================
// SESIONES DE ENTRENAMIENTO (EJEMPLO)
// ============================================

const hoy = new Date();
const formatDate = (date: Date) => date.toISOString().split("T")[0];

export const sesionesData: SesionEntrenamiento[] = [
  {
    id: "ses-001",
    clienteId: "cli-001",
    clienteNombre: "María García López",
    fecha: formatDate(hoy),
    diaSemana: hoy.getDay(),
    nombre: "Torso A - Empuje",
    ejercicios: [
      {
        id: "ea-001",
        ejercicioId: "ej-001",
        orden: 1,
        series: [
          {
            id: "s1",
            numero: 1,
            repeticiones: 8,
            peso: 40,
            rpe: 7,
            descansoSegundos: 180,
            completada: true,
            repeticionesReales: 8,
            pesoReal: 40,
            rpeReal: 7,
          },
          {
            id: "s2",
            numero: 2,
            repeticiones: 8,
            peso: 40,
            rpe: 7,
            descansoSegundos: 180,
            completada: true,
            repeticionesReales: 8,
            pesoReal: 40,
            rpeReal: 7.5,
          },
          {
            id: "s3",
            numero: 3,
            repeticiones: 8,
            peso: 40,
            rpe: 8,
            descansoSegundos: 180,
            completada: true,
            repeticionesReales: 7,
            pesoReal: 40,
            rpeReal: 8,
          },
          { id: "s4", numero: 4, repeticiones: 8, peso: 40, rpe: 8, descansoSegundos: 180, completada: false },
        ],
        tipoProgresion: "incremento_kg",
        incrementoSemanal: 2.5,
      },
      {
        id: "ea-002",
        ejercicioId: "ej-016",
        orden: 2,
        series: [
          { id: "s5", numero: 1, repeticiones: 10, peso: 25, rpe: 7, descansoSegundos: 120, completada: true },
          { id: "s6", numero: 2, repeticiones: 10, peso: 25, rpe: 7, descansoSegundos: 120, completada: true },
          { id: "s7", numero: 3, repeticiones: 10, peso: 25, rpe: 8, descansoSegundos: 120, completada: true },
        ],
      },
      {
        id: "ea-003",
        ejercicioId: "ej-018",
        orden: 3,
        series: [
          { id: "s8", numero: 1, repeticiones: 15, peso: 8, rpe: 7, descansoSegundos: 60, completada: true },
          { id: "s9", numero: 2, repeticiones: 15, peso: 8, rpe: 8, descansoSegundos: 60, completada: true },
          { id: "s10", numero: 3, repeticiones: 15, peso: 8, rpe: 8, descansoSegundos: 60, completada: true },
        ],
      },
    ],
    estado: "parcial",
    duracionMinutos: 60,
    volumenTotal: 3520,
  },
  {
    id: "ses-002",
    clienteId: "cli-002",
    clienteNombre: "Carlos Rodríguez Pérez",
    fecha: formatDate(hoy),
    diaSemana: hoy.getDay(),
    nombre: "Full Body A",
    ejercicios: [
      {
        id: "ea-004",
        ejercicioId: "ej-012",
        orden: 1,
        series: [
          { id: "s11", numero: 1, repeticiones: 12, peso: 100, descansoSegundos: 120, completada: false },
          { id: "s12", numero: 2, repeticiones: 12, peso: 100, descansoSegundos: 120, completada: false },
          { id: "s13", numero: 3, repeticiones: 12, peso: 100, descansoSegundos: 120, completada: false },
        ],
        notas: "Usar prensa en lugar de sentadilla por lesión lumbar",
      },
    ],
    estado: "pendiente",
    duracionMinutos: 45,
  },
  {
    id: "ses-003",
    clienteId: "cli-003",
    clienteNombre: "Ana Martínez Sánchez",
    fecha: formatDate(new Date(hoy.getTime() - 24 * 60 * 60 * 1000)),
    diaSemana: (hoy.getDay() + 6) % 7,
    nombre: "Push Day",
    ejercicios: [],
    estado: "completada",
    duracionMinutos: 75,
    duracionReal: 80,
    volumenTotal: 5200,
  },
];

// ============================================
// ESTADÍSTICAS
// ============================================

export const getTrainerStats = (): TrainerStats => {
  const ejerciciosConVideo = ejerciciosData.filter((e) => e.videoUrl).length;
  const clientesActivos = clientesEntrenamientoData.filter((c) => c.adherencia.porcentajeSesiones > 50).length;
  const adherenciaPromedio = Math.round(
    clientesEntrenamientoData.reduce((acc, c) => acc + c.adherencia.porcentajeSesiones, 0) /
      clientesEntrenamientoData.length,
  );
  const clientesConLesiones = clientesEntrenamientoData.filter((c) => c.lesiones.length > 0).length;

  return {
    totalEjercicios: ejerciciosData.length,
    ejerciciosConVideo,
    totalClientes: clientesEntrenamientoData.length,
    clientesActivos,
    adherenciaPromedio,
    sesionesEstaSemana: sesionesData.length,
    sesionesCompletadas: sesionesData.filter((s) => s.estado === "completada").length,
    clientesConLesiones,
  };
};

// ============================================
// OPCIONES PARA FILTROS Y SELECTS
// ============================================

export const gruposMusculares: { value: GrupoMuscular | "todos"; label: string }[] = [
  { value: "todos", label: "Todos los grupos" },
  { value: "pecho", label: "Pecho" },
  { value: "espalda", label: "Espalda" },
  { value: "hombros", label: "Hombros" },
  { value: "biceps", label: "Bíceps" },
  { value: "triceps", label: "Tríceps" },
  { value: "cuadriceps", label: "Cuádriceps" },
  { value: "isquiotibiales", label: "Isquiotibiales" },
  { value: "gluteos", label: "Glúteos" },
  { value: "gemelos", label: "Gemelos" },
  { value: "core", label: "Core" },
  { value: "antebrazos", label: "Antebrazos" },
  { value: "trapecio", label: "Trapecio" },
  { value: "full_body", label: "Full Body" },
];

export const tiposMaterial: { value: TipoMaterial | "todos"; label: string }[] = [
  { value: "todos", label: "Todo el material" },
  { value: "barra", label: "Barra" },
  { value: "mancuernas", label: "Mancuernas" },
  { value: "kettlebell", label: "Kettlebell" },
  { value: "maquina", label: "Máquina" },
  { value: "poleas", label: "Poleas" },
  { value: "peso_corporal", label: "Peso corporal" },
  { value: "bandas_elasticas", label: "Bandas elásticas" },
  { value: "suspension_trx", label: "TRX / Suspensión" },
  { value: "landmine", label: "Landmine" },
  { value: "sin_material", label: "Sin material" },
];

export const nivelesDificultad: { value: NivelDificultad | "todos"; label: string }[] = [
  { value: "todos", label: "Todos los niveles" },
  { value: "principiante", label: "Principiante" },
  { value: "intermedio", label: "Intermedio" },
  { value: "avanzado", label: "Avanzado" },
];

export const plantillasEntrenamiento: {
  value: TipoPlantilla;
  label: string;
  descripcion: string;
  diasSemana: number;
}[] = [
  { value: "full_body", label: "Full Body", descripcion: "Entrena todo el cuerpo cada sesión", diasSemana: 3 },
  {
    value: "torso_pierna",
    label: "Torso / Pierna",
    descripcion: "Alterna días de tren superior e inferior",
    diasSemana: 4,
  },
  { value: "ppl", label: "Push / Pull / Legs", descripcion: "Divide por patrones de movimiento", diasSemana: 6 },
  { value: "upper_lower", label: "Upper / Lower", descripcion: "Divide en tren superior e inferior", diasSemana: 4 },
  { value: "personalizado", label: "Personalizado", descripcion: "Rutina completamente personalizada", diasSemana: 0 },
];

export const tiposLesion: { value: TipoLesion; label: string; color: string }[] = [
  { value: "lumbar", label: "Lumbar", color: "bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200" },
  {
    value: "rodilla",
    label: "Rodilla",
    color: "bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-200",
  },
  { value: "hombro", label: "Hombro", color: "bg-amber-100 text-amber-800 dark:bg-amber-900 dark:text-amber-200" },
  {
    value: "cervical",
    label: "Cervical",
    color: "bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200",
  },
  { value: "codo", label: "Codo", color: "bg-lime-100 text-lime-800 dark:bg-lime-900 dark:text-lime-200" },
  { value: "muneca", label: "Muñeca", color: "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200" },
  { value: "cadera", label: "Cadera", color: "bg-teal-100 text-teal-800 dark:bg-teal-900 dark:text-teal-200" },
  { value: "tobillo", label: "Tobillo", color: "bg-cyan-100 text-cyan-800 dark:bg-cyan-900 dark:text-cyan-200" },
];

export const tiposRestriccion: { value: TipoRestriccion; label: string; color: string }[] = [
  {
    value: "sin_barra",
    label: "Sin barra",
    color: "bg-slate-100 text-slate-800 dark:bg-slate-800 dark:text-slate-200",
  },
  {
    value: "solo_mancuernas",
    label: "Solo mancuernas",
    color: "bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200",
  },
  {
    value: "sin_impacto",
    label: "Sin impacto",
    color: "bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200",
  },
  {
    value: "sin_flexion_rodilla",
    label: "Sin flexión rodilla",
    color: "bg-pink-100 text-pink-800 dark:bg-pink-900 dark:text-pink-200",
  },
  {
    value: "sin_press_vertical",
    label: "Sin press vertical",
    color: "bg-rose-100 text-rose-800 dark:bg-rose-900 dark:text-rose-200",
  },
  {
    value: "sin_peso_libre",
    label: "Sin peso libre",
    color: "bg-indigo-100 text-indigo-800 dark:bg-indigo-900 dark:text-indigo-200",
  },
  {
    value: "sin_rotacion_externa",
    label: "Sin rotación externa",
    color: "bg-violet-100 text-violet-800 dark:bg-violet-900 dark:text-violet-200",
  },
  {
    value: "rango_limitado",
    label: "Rango limitado",
    color: "bg-fuchsia-100 text-fuchsia-800 dark:bg-fuchsia-900 dark:text-fuchsia-200",
  },
];

export const tiposProgresion: { value: string; label: string; descripcion: string }[] = [
  { value: "porcentaje_1rm", label: "% del 1RM", descripcion: "Incrementa el porcentaje del máximo" },
  { value: "incremento_kg", label: "+kg semanales", descripcion: "Añade peso fijo cada semana" },
  { value: "incremento_reps", label: "+reps semanales", descripcion: "Añade repeticiones manteniendo peso" },
  { value: "autoregulacion", label: "Autorregulación (RPE)", descripcion: "Ajusta según el RPE reportado" },
];
