import type { Ejercicio, SustitucionEjercicio, GrupoMuscular, TipoMaterial, NivelDificultad } from "./schema";

// ============================================
// BIBLIOTECA DE EJERCICIOS
// ============================================

export const ejerciciosData: Ejercicio[] = [
  // PECHO
  {
    id: "ej-001",
    nombre: "Press de banca con barra",
    nombreIngles: "Barbell Bench Press",
    descripcion: "Ejercicio principal para el desarrollo del pectoral mayor",
    grupoMuscular: "pecho",
    gruposSecundarios: ["triceps", "hombros"],
    material: ["barra"],
    nivel: "intermedio",
    videoUrl: "https://www.youtube.com/embed/rT7DgCr-3pg",
    thumbnailUrl: "/ejercicios/bench-press.jpg",
    instrucciones: [
      "Acuéstate en el banco con los pies apoyados en el suelo",
      "Agarra la barra con un agarre ligeramente más ancho que los hombros",
      "Baja la barra de forma controlada hasta el pecho",
      "Empuja la barra hacia arriba hasta extender los brazos",
    ],
    erroresComunes: ["Rebotar la barra en el pecho", "Arquear excesivamente la espalda", "No controlar la bajada"],
    sustituciones: ["ej-002", "ej-003"],
    etiquetas: ["compuesto", "fuerza", "principal"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-002",
    nombre: "Press de banca con mancuernas",
    nombreIngles: "Dumbbell Bench Press",
    descripcion: "Variante con mayor rango de movimiento",
    grupoMuscular: "pecho",
    gruposSecundarios: ["triceps", "hombros"],
    material: ["mancuernas"],
    nivel: "principiante",
    videoUrl: "https://www.youtube.com/embed/VmB1G1K7v94",
    instrucciones: [
      "Siéntate en el banco con una mancuerna en cada mano",
      "Acuéstate llevando las mancuernas al pecho",
      "Presiona hacia arriba hasta extender los brazos",
      "Baja de forma controlada",
    ],
    sustituciones: ["ej-001", "ej-003"],
    etiquetas: ["compuesto", "fuerza"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-003",
    nombre: "Flexiones",
    nombreIngles: "Push-ups",
    descripcion: "Ejercicio de peso corporal para pecho y tríceps",
    grupoMuscular: "pecho",
    gruposSecundarios: ["triceps", "hombros", "core"],
    material: ["peso_corporal"],
    nivel: "principiante",
    videoUrl: "https://www.youtube.com/embed/IODxDxX7oi4",
    sustituciones: ["ej-001", "ej-002"],
    etiquetas: ["peso_corporal", "básico"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-004",
    nombre: "Aperturas con mancuernas",
    nombreIngles: "Dumbbell Flyes",
    grupoMuscular: "pecho",
    material: ["mancuernas"],
    nivel: "principiante",
    videoUrl: "https://www.youtube.com/embed/eozdVDA78K0",
    sustituciones: ["ej-005"],
    etiquetas: ["aislamiento", "accesorio"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-005",
    nombre: "Cruces en polea",
    nombreIngles: "Cable Crossover",
    grupoMuscular: "pecho",
    material: ["poleas"],
    nivel: "intermedio",
    videoUrl: "https://www.youtube.com/embed/taI4XduLpTk",
    sustituciones: ["ej-004"],
    etiquetas: ["aislamiento", "accesorio"],
    activo: true,
    createdAt: "2024-01-01",
  },
  // ESPALDA
  {
    id: "ej-006",
    nombre: "Dominadas",
    nombreIngles: "Pull-ups",
    descripcion: "Ejercicio principal para el desarrollo del dorsal",
    grupoMuscular: "espalda",
    gruposSecundarios: ["biceps", "antebrazos"],
    material: ["peso_corporal"],
    nivel: "intermedio",
    videoUrl: "https://www.youtube.com/embed/eGo4IYlbE5g",
    sustituciones: ["ej-007", "ej-008"],
    etiquetas: ["compuesto", "fuerza", "principal"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-007",
    nombre: "Jalón al pecho",
    nombreIngles: "Lat Pulldown",
    grupoMuscular: "espalda",
    gruposSecundarios: ["biceps"],
    material: ["poleas", "maquina"],
    nivel: "principiante",
    videoUrl: "https://www.youtube.com/embed/CAwf7n6Luuc",
    sustituciones: ["ej-006"],
    etiquetas: ["compuesto", "accesorio"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-008",
    nombre: "Remo con barra",
    nombreIngles: "Barbell Row",
    grupoMuscular: "espalda",
    gruposSecundarios: ["biceps", "core"],
    material: ["barra"],
    nivel: "intermedio",
    videoUrl: "https://www.youtube.com/embed/FWJR5Ve8bnQ",
    sustituciones: ["ej-009"],
    etiquetas: ["compuesto", "fuerza", "principal"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-009",
    nombre: "Remo con mancuerna",
    nombreIngles: "Dumbbell Row",
    grupoMuscular: "espalda",
    gruposSecundarios: ["biceps"],
    material: ["mancuernas"],
    nivel: "principiante",
    videoUrl: "https://www.youtube.com/embed/pYcpY20QaE8",
    sustituciones: ["ej-008"],
    etiquetas: ["compuesto", "accesorio"],
    activo: true,
    createdAt: "2024-01-01",
  },
  // PIERNAS
  {
    id: "ej-010",
    nombre: "Sentadilla con barra",
    nombreIngles: "Barbell Squat",
    descripcion: "El rey de los ejercicios de pierna",
    grupoMuscular: "cuadriceps",
    gruposSecundarios: ["gluteos", "isquiotibiales", "core"],
    material: ["barra"],
    nivel: "intermedio",
    videoUrl: "https://www.youtube.com/embed/ultWZbUMPL8",
    sustituciones: ["ej-011", "ej-012"],
    etiquetas: ["compuesto", "fuerza", "principal"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-011",
    nombre: "Sentadilla goblet",
    nombreIngles: "Goblet Squat",
    grupoMuscular: "cuadriceps",
    gruposSecundarios: ["gluteos", "core"],
    material: ["mancuernas", "kettlebell"],
    nivel: "principiante",
    videoUrl: "https://www.youtube.com/embed/MeIiIdhvXT4",
    sustituciones: ["ej-010"],
    etiquetas: ["compuesto", "básico"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-012",
    nombre: "Prensa de piernas",
    nombreIngles: "Leg Press",
    grupoMuscular: "cuadriceps",
    gruposSecundarios: ["gluteos"],
    material: ["maquina"],
    nivel: "principiante",
    videoUrl: "https://www.youtube.com/embed/IZxyjW7MPJQ",
    sustituciones: ["ej-010", "ej-011"],
    etiquetas: ["compuesto", "accesorio"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-013",
    nombre: "Peso muerto rumano",
    nombreIngles: "Romanian Deadlift",
    grupoMuscular: "isquiotibiales",
    gruposSecundarios: ["gluteos", "espalda"],
    material: ["barra", "mancuernas"],
    nivel: "intermedio",
    videoUrl: "https://www.youtube.com/embed/JCXUYuzwNrM",
    sustituciones: ["ej-014"],
    etiquetas: ["compuesto", "fuerza"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-014",
    nombre: "Curl femoral",
    nombreIngles: "Leg Curl",
    grupoMuscular: "isquiotibiales",
    material: ["maquina"],
    nivel: "principiante",
    videoUrl: "https://www.youtube.com/embed/1Tq3QdYUuHs",
    sustituciones: ["ej-013"],
    etiquetas: ["aislamiento", "accesorio"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-015",
    nombre: "Hip Thrust",
    nombreIngles: "Hip Thrust",
    grupoMuscular: "gluteos",
    gruposSecundarios: ["isquiotibiales"],
    material: ["barra"],
    nivel: "intermedio",
    videoUrl: "https://www.youtube.com/embed/SEdqd1n0cvg",
    etiquetas: ["compuesto", "principal"],
    activo: true,
    createdAt: "2024-01-01",
  },
  // HOMBROS
  {
    id: "ej-016",
    nombre: "Press militar con barra",
    nombreIngles: "Overhead Press",
    grupoMuscular: "hombros",
    gruposSecundarios: ["triceps", "core"],
    material: ["barra"],
    nivel: "intermedio",
    videoUrl: "https://www.youtube.com/embed/2yjwXTZQDDI",
    sustituciones: ["ej-017"],
    etiquetas: ["compuesto", "fuerza", "principal"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-017",
    nombre: "Press de hombros con mancuernas",
    nombreIngles: "Dumbbell Shoulder Press",
    grupoMuscular: "hombros",
    gruposSecundarios: ["triceps"],
    material: ["mancuernas"],
    nivel: "principiante",
    videoUrl: "https://www.youtube.com/embed/qEwKCR5JCog",
    sustituciones: ["ej-016"],
    etiquetas: ["compuesto", "accesorio"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-018",
    nombre: "Elevaciones laterales",
    nombreIngles: "Lateral Raises",
    grupoMuscular: "hombros",
    material: ["mancuernas"],
    nivel: "principiante",
    videoUrl: "https://www.youtube.com/embed/3VcKaXpzqRo",
    etiquetas: ["aislamiento", "accesorio"],
    activo: true,
    createdAt: "2024-01-01",
  },
  // BRAZOS
  {
    id: "ej-019",
    nombre: "Curl de bíceps con barra",
    nombreIngles: "Barbell Curl",
    grupoMuscular: "biceps",
    material: ["barra"],
    nivel: "principiante",
    videoUrl: "https://www.youtube.com/embed/kwG2ipFRgfo",
    sustituciones: ["ej-020"],
    etiquetas: ["aislamiento", "accesorio"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-020",
    nombre: "Curl de bíceps con mancuernas",
    nombreIngles: "Dumbbell Curl",
    grupoMuscular: "biceps",
    material: ["mancuernas"],
    nivel: "principiante",
    videoUrl: "https://www.youtube.com/embed/ykJmrZ5v0Oo",
    sustituciones: ["ej-019"],
    etiquetas: ["aislamiento", "accesorio"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-021",
    nombre: "Extensión de tríceps en polea",
    nombreIngles: "Tricep Pushdown",
    grupoMuscular: "triceps",
    material: ["poleas"],
    nivel: "principiante",
    videoUrl: "https://www.youtube.com/embed/2-LAMcpzODU",
    sustituciones: ["ej-022"],
    etiquetas: ["aislamiento", "accesorio"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-022",
    nombre: "Fondos en paralelas",
    nombreIngles: "Dips",
    grupoMuscular: "triceps",
    gruposSecundarios: ["pecho", "hombros"],
    material: ["peso_corporal"],
    nivel: "intermedio",
    videoUrl: "https://www.youtube.com/embed/2z8JmcrW-As",
    sustituciones: ["ej-021"],
    etiquetas: ["compuesto", "peso_corporal"],
    activo: true,
    createdAt: "2024-01-01",
  },
  // CORE
  {
    id: "ej-023",
    nombre: "Plancha",
    nombreIngles: "Plank",
    grupoMuscular: "core",
    material: ["peso_corporal"],
    nivel: "principiante",
    videoUrl: "https://www.youtube.com/embed/ASdvN_XEl_c",
    etiquetas: ["isométrico", "básico"],
    activo: true,
    createdAt: "2024-01-01",
  },
  {
    id: "ej-024",
    nombre: "Ab Wheel Rollout",
    nombreIngles: "Ab Wheel Rollout",
    grupoMuscular: "core",
    material: ["sin_material"],
    nivel: "intermedio",
    videoUrl: "https://www.youtube.com/embed/rqiTPdK1c_I",
    etiquetas: ["dinamico", "avanzado"],
    activo: true,
    createdAt: "2024-01-01",
  },
];

// ============================================
// SUSTITUCIONES DE EJERCICIOS
// ============================================

export const sustitucionesData: SustitucionEjercicio[] = [
  {
    ejercicioOriginalId: "ej-001",
    ejercicioSustitutoId: "ej-002",
    ejercicioSustitutoNombre: "Press de banca con mancuernas",
    razon: "material",
    equivalencia: 90,
    notas: "Mayor rango de movimiento, menos peso total",
  },
  {
    ejercicioOriginalId: "ej-001",
    ejercicioSustitutoId: "ej-003",
    ejercicioSustitutoNombre: "Flexiones",
    razon: "material",
    equivalencia: 70,
    notas: "Sin equipamiento, ajustar volumen",
  },
  {
    ejercicioOriginalId: "ej-010",
    ejercicioSustitutoId: "ej-012",
    ejercicioSustitutoNombre: "Prensa de piernas",
    razon: "lesion",
    equivalencia: 75,
    notas: "Para problemas lumbares, menor demanda de core",
  },
  {
    ejercicioOriginalId: "ej-016",
    ejercicioSustitutoId: "ej-017",
    ejercicioSustitutoNombre: "Press de hombros con mancuernas",
    razon: "lesion",
    equivalencia: 85,
    notas: "Mejor para problemas de hombro, permite rotación natural",
  },
];

// ============================================
// OPCIONES PARA FILTROS Y SELECTS
// ============================================

export const gruposMusculares: { value: GrupoMuscular | "todos"; label: string }[] = [
  { value: "todos", label: "Todos los grupos" },
  { value: "pecho", label: "Pecho" },
  { value: "espalda", label: "Espalda" },
  { value: "hombros", label: "Hombros" },
  { value: "biceps", label: "Bíceps" },
  { value: "triceps", label: "Tríceps" },
  { value: "cuadriceps", label: "Cuádriceps" },
  { value: "isquiotibiales", label: "Isquiotibiales" },
  { value: "gluteos", label: "Glúteos" },
  { value: "gemelos", label: "Gemelos" },
  { value: "core", label: "Core" },
  { value: "antebrazos", label: "Antebrazos" },
  { value: "trapecio", label: "Trapecio" },
  { value: "full_body", label: "Full Body" },
];

export const tiposMaterial: { value: TipoMaterial | "todos"; label: string }[] = [
  { value: "todos", label: "Todo el material" },
  { value: "barra", label: "Barra" },
  { value: "mancuernas", label: "Mancuernas" },
  { value: "kettlebell", label: "Kettlebell" },
  { value: "maquina", label: "Máquina" },
  { value: "poleas", label: "Poleas" },
  { value: "peso_corporal", label: "Peso corporal" },
  { value: "bandas_elasticas", label: "Bandas elásticas" },
  { value: "suspension_trx", label: "TRX / Suspensión" },
  { value: "landmine", label: "Landmine" },
  { value: "sin_material", label: "Sin material" },
];

export const nivelesDificultad: { value: NivelDificultad | "todos"; label: string }[] = [
  { value: "todos", label: "Todos los niveles" },
  { value: "principiante", label: "Principiante" },
  { value: "intermedio", label: "Intermedio" },
  { value: "avanzado", label: "Avanzado" },
];
