import { Alimento } from "./schema";

// ============================================
// ALIMENTOS ESTÁTICOS
// ============================================

export const alimentosData: Alimento[] = [
  {
    id: "alim-001",
    nombre: "Pechuga de pollo",
    categoria: "proteinas",
    calorias: 165,
    proteinas: 31,
    carbohidratos: 0,
    grasas: 3.6,
    fibra: 0,
    origen: "manual",
    etiquetas: ["alto_proteina", "sin_gluten"],
    createdAt: "2024-01-15",
  },
  {
    id: "alim-002",
    nombre: "Arroz integral",
    categoria: "carbohidratos",
    calorias: 362,
    proteinas: 7.5,
    carbohidratos: 76,
    grasas: 2.7,
    fibra: 3.4,
    origen: "manual",
    etiquetas: ["sin_gluten", "vegano"],
    createdAt: "2024-01-15",
  },
  {
    id: "alim-003",
    nombre: "Salmón atlántico",
    categoria: "proteinas",
    calorias: 208,
    proteinas: 20,
    carbohidratos: 0,
    grasas: 13,
    fibra: 0,
    origen: "open_food_facts",
    etiquetas: ["alto_proteina", "omega3", "sin_gluten"],
    createdAt: "2024-01-16",
  },
  {
    id: "alim-004",
    nombre: "Brócoli",
    categoria: "verduras",
    calorias: 34,
    proteinas: 2.8,
    carbohidratos: 7,
    grasas: 0.4,
    fibra: 2.6,
    origen: "bedca",
    etiquetas: ["vegano", "sin_gluten", "bajo_calorias"],
    createdAt: "2024-01-16",
  },
  {
    id: "alim-005",
    nombre: "Huevo entero",
    categoria: "proteinas",
    calorias: 155,
    proteinas: 13,
    carbohidratos: 1.1,
    grasas: 11,
    fibra: 0,
    origen: "manual",
    etiquetas: ["alto_proteina", "sin_gluten", "vegetariano"],
    createdAt: "2024-01-17",
  },
  {
    id: "alim-006",
    nombre: "Avena en copos",
    categoria: "carbohidratos",
    calorias: 389,
    proteinas: 16.9,
    carbohidratos: 66,
    grasas: 6.9,
    fibra: 10.6,
    origen: "manual",
    etiquetas: ["alto_fibra", "vegano"],
    createdAt: "2024-01-17",
  },
  {
    id: "alim-007",
    nombre: "Aguacate",
    categoria: "grasas",
    calorias: 160,
    proteinas: 2,
    carbohidratos: 9,
    grasas: 15,
    fibra: 7,
    origen: "open_food_facts",
    etiquetas: ["vegano", "sin_gluten", "grasas_saludables"],
    createdAt: "2024-01-18",
  },
  {
    id: "alim-008",
    nombre: "Plátano",
    categoria: "frutas",
    calorias: 89,
    proteinas: 1.1,
    carbohidratos: 23,
    grasas: 0.3,
    fibra: 2.6,
    origen: "bedca",
    etiquetas: ["vegano", "sin_gluten"],
    createdAt: "2024-01-18",
  },
  {
    id: "alim-009",
    nombre: "Yogur griego natural",
    categoria: "lacteos",
    calorias: 97,
    proteinas: 9,
    carbohidratos: 3.6,
    grasas: 5,
    fibra: 0,
    origen: "manual",
    etiquetas: ["alto_proteina", "sin_gluten", "vegetariano"],
    createdAt: "2024-01-19",
  },
  {
    id: "alim-010",
    nombre: "Almendras",
    categoria: "frutos_secos",
    calorias: 579,
    proteinas: 21,
    carbohidratos: 22,
    grasas: 49,
    fibra: 12.5,
    origen: "open_food_facts",
    etiquetas: ["vegano", "sin_gluten", "grasas_saludables"],
    createdAt: "2024-01-19",
  },
  {
    id: "alim-011",
    nombre: "Lentejas cocidas",
    categoria: "legumbres",
    calorias: 116,
    proteinas: 9,
    carbohidratos: 20,
    grasas: 0.4,
    fibra: 8,
    origen: "bedca",
    etiquetas: ["vegano", "sin_gluten", "alto_fibra", "alto_proteina"],
    createdAt: "2024-01-20",
  },
  {
    id: "alim-012",
    nombre: "Espinacas frescas",
    categoria: "verduras",
    calorias: 23,
    proteinas: 2.9,
    carbohidratos: 3.6,
    grasas: 0.4,
    fibra: 2.2,
    origen: "manual",
    etiquetas: ["vegano", "sin_gluten", "bajo_calorias"],
    createdAt: "2024-01-20",
  },
  {
    id: "alim-013",
    nombre: "Boniato/Batata",
    categoria: "carbohidratos",
    calorias: 86,
    proteinas: 1.6,
    carbohidratos: 20,
    grasas: 0.1,
    fibra: 3,
    origen: "manual",
    etiquetas: ["vegano", "sin_gluten"],
    createdAt: "2024-01-21",
  },
  {
    id: "alim-014",
    nombre: "Atún en conserva al natural",
    categoria: "proteinas",
    calorias: 116,
    proteinas: 26,
    carbohidratos: 0,
    grasas: 1,
    fibra: 0,
    origen: "open_food_facts",
    etiquetas: ["alto_proteina", "sin_gluten", "bajo_grasa"],
    createdAt: "2024-01-21",
  },
  {
    id: "alim-015",
    nombre: "Aceite de oliva virgen extra",
    categoria: "grasas",
    calorias: 884,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 100,
    fibra: 0,
    origen: "manual",
    etiquetas: ["vegano", "sin_gluten", "grasas_saludables"],
    createdAt: "2024-01-22",
  },
];

// ============================================
// OPCIONES PARA FILTROS Y SELECT
// ============================================

export const categoriasAlimentos = [
  { value: "proteinas", label: "Proteínas" },
  { value: "carbohidratos", label: "Carbohidratos" },
  { value: "grasas", label: "Grasas" },
  { value: "verduras", label: "Verduras" },
  { value: "frutas", label: "Frutas" },
  { value: "lacteos", label: "Lácteos" },
  { value: "legumbres", label: "Legumbres" },
  { value: "frutos_secos", label: "Frutos Secos" },
  { value: "otros", label: "Otros" },
];

export const origenesAlimentos = [
  { value: "manual", label: "Manual" },
  { value: "open_food_facts", label: "Open Food Facts" },
  { value: "bedca", label: "BEDCA" },
];
