import { Alimento, Receta, MenuSemanal, Sustitucion, Restriccion, DietaStats } from "./schema";

// ============================================
// ALIMENTOS ESTÁTICOS
// ============================================

export const alimentosData: Alimento[] = [
  {
    id: "alim-001",
    nombre: "Pechuga de pollo",
    categoria: "proteinas",
    calorias: 165,
    proteinas: 31,
    carbohidratos: 0,
    grasas: 3.6,
    fibra: 0,
    origen: "manual",
    etiquetas: ["alto_proteina", "sin_gluten"],
    createdAt: "2024-01-15",
  },
  {
    id: "alim-002",
    nombre: "Arroz integral",
    categoria: "carbohidratos",
    calorias: 362,
    proteinas: 7.5,
    carbohidratos: 76,
    grasas: 2.7,
    fibra: 3.4,
    origen: "manual",
    etiquetas: ["sin_gluten", "vegano"],
    createdAt: "2024-01-15",
  },
  {
    id: "alim-003",
    nombre: "Salmón atlántico",
    categoria: "proteinas",
    calorias: 208,
    proteinas: 20,
    carbohidratos: 0,
    grasas: 13,
    fibra: 0,
    origen: "open_food_facts",
    etiquetas: ["alto_proteina", "omega3", "sin_gluten"],
    createdAt: "2024-01-16",
  },
  {
    id: "alim-004",
    nombre: "Brócoli",
    categoria: "verduras",
    calorias: 34,
    proteinas: 2.8,
    carbohidratos: 7,
    grasas: 0.4,
    fibra: 2.6,
    origen: "bedca",
    etiquetas: ["vegano", "sin_gluten", "bajo_calorias"],
    createdAt: "2024-01-16",
  },
  {
    id: "alim-005",
    nombre: "Huevo entero",
    categoria: "proteinas",
    calorias: 155,
    proteinas: 13,
    carbohidratos: 1.1,
    grasas: 11,
    fibra: 0,
    origen: "manual",
    etiquetas: ["alto_proteina", "sin_gluten", "vegetariano"],
    createdAt: "2024-01-17",
  },
  {
    id: "alim-006",
    nombre: "Avena en copos",
    categoria: "carbohidratos",
    calorias: 389,
    proteinas: 16.9,
    carbohidratos: 66,
    grasas: 6.9,
    fibra: 10.6,
    origen: "manual",
    etiquetas: ["alto_fibra", "vegano"],
    createdAt: "2024-01-17",
  },
  {
    id: "alim-007",
    nombre: "Aguacate",
    categoria: "grasas",
    calorias: 160,
    proteinas: 2,
    carbohidratos: 9,
    grasas: 15,
    fibra: 7,
    origen: "open_food_facts",
    etiquetas: ["vegano", "sin_gluten", "grasas_saludables"],
    createdAt: "2024-01-18",
  },
  {
    id: "alim-008",
    nombre: "Plátano",
    categoria: "frutas",
    calorias: 89,
    proteinas: 1.1,
    carbohidratos: 23,
    grasas: 0.3,
    fibra: 2.6,
    origen: "bedca",
    etiquetas: ["vegano", "sin_gluten"],
    createdAt: "2024-01-18",
  },
  {
    id: "alim-009",
    nombre: "Yogur griego natural",
    categoria: "lacteos",
    calorias: 97,
    proteinas: 9,
    carbohidratos: 3.6,
    grasas: 5,
    fibra: 0,
    origen: "manual",
    etiquetas: ["alto_proteina", "sin_gluten", "vegetariano"],
    createdAt: "2024-01-19",
  },
  {
    id: "alim-010",
    nombre: "Almendras",
    categoria: "frutos_secos",
    calorias: 579,
    proteinas: 21,
    carbohidratos: 22,
    grasas: 49,
    fibra: 12.5,
    origen: "open_food_facts",
    etiquetas: ["vegano", "sin_gluten", "grasas_saludables"],
    createdAt: "2024-01-19",
  },
  {
    id: "alim-011",
    nombre: "Lentejas cocidas",
    categoria: "legumbres",
    calorias: 116,
    proteinas: 9,
    carbohidratos: 20,
    grasas: 0.4,
    fibra: 8,
    origen: "bedca",
    etiquetas: ["vegano", "sin_gluten", "alto_fibra", "alto_proteina"],
    createdAt: "2024-01-20",
  },
  {
    id: "alim-012",
    nombre: "Espinacas frescas",
    categoria: "verduras",
    calorias: 23,
    proteinas: 2.9,
    carbohidratos: 3.6,
    grasas: 0.4,
    fibra: 2.2,
    origen: "manual",
    etiquetas: ["vegano", "sin_gluten", "bajo_calorias"],
    createdAt: "2024-01-20",
  },
  {
    id: "alim-013",
    nombre: "Boniato/Batata",
    categoria: "carbohidratos",
    calorias: 86,
    proteinas: 1.6,
    carbohidratos: 20,
    grasas: 0.1,
    fibra: 3,
    origen: "manual",
    etiquetas: ["vegano", "sin_gluten"],
    createdAt: "2024-01-21",
  },
  {
    id: "alim-014",
    nombre: "Atún en conserva al natural",
    categoria: "proteinas",
    calorias: 116,
    proteinas: 26,
    carbohidratos: 0,
    grasas: 1,
    fibra: 0,
    origen: "open_food_facts",
    etiquetas: ["alto_proteina", "sin_gluten", "bajo_grasa"],
    createdAt: "2024-01-21",
  },
  {
    id: "alim-015",
    nombre: "Aceite de oliva virgen extra",
    categoria: "grasas",
    calorias: 884,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 100,
    fibra: 0,
    origen: "manual",
    etiquetas: ["vegano", "sin_gluten", "grasas_saludables"],
    createdAt: "2024-01-22",
  },
];

// ============================================
// RECETAS ESTÁTICAS
// ============================================

export const recetasData: Receta[] = [
  {
    id: "rec-001",
    nombre: "Bowl de pollo con arroz integral",
    descripcion: "Un bowl nutritivo y equilibrado, perfecto para después del entrenamiento",
    tipoComida: "comida",
    tiempoPreparacion: 35,
    porciones: 2,
    dificultad: "facil",
    ingredientes: [
      {
        alimentoId: "alim-001",
        nombre: "Pechuga de pollo",
        cantidad: 300,
        calorias: 495,
        proteinas: 93,
        carbohidratos: 0,
        grasas: 10.8,
      },
      {
        alimentoId: "alim-002",
        nombre: "Arroz integral",
        cantidad: 150,
        calorias: 543,
        proteinas: 11.25,
        carbohidratos: 114,
        grasas: 4.05,
      },
      {
        alimentoId: "alim-004",
        nombre: "Brócoli",
        cantidad: 200,
        calorias: 68,
        proteinas: 5.6,
        carbohidratos: 14,
        grasas: 0.8,
      },
      {
        alimentoId: "alim-015",
        nombre: "Aceite de oliva virgen extra",
        cantidad: 15,
        calorias: 132.6,
        proteinas: 0,
        carbohidratos: 0,
        grasas: 15,
      },
    ],
    instrucciones: [
      "Cocinar el arroz integral según las instrucciones del paquete",
      "Cortar la pechuga de pollo en tiras y sazonar con sal, pimienta y especias al gusto",
      "Cocinar el pollo a la plancha con un poco de aceite de oliva",
      "Cocinar el brócoli al vapor durante 5-7 minutos",
      "Montar el bowl con arroz, pollo y brócoli",
      "Aliñar con el resto del aceite de oliva",
    ],
    caloriasTotal: 1238.6,
    proteinasTotal: 109.85,
    carbohidratosTotal: 128,
    grasasTotal: 30.65,
    caloriasPorcion: 619.3,
    proteinasPorcion: 54.93,
    carbohidratosPorcion: 64,
    grasasPorcion: 15.33,
    etiquetas: ["alto_proteina", "sin_gluten", "post_entreno"],
    estado: "publicado",
    createdAt: "2024-02-01",
  },
  {
    id: "rec-002",
    nombre: "Tortilla de claras con espinacas",
    descripcion: "Desayuno rico en proteínas y bajo en calorías",
    tipoComida: "desayuno",
    tiempoPreparacion: 15,
    porciones: 1,
    dificultad: "facil",
    ingredientes: [
      {
        alimentoId: "alim-005",
        nombre: "Huevo entero",
        cantidad: 150,
        calorias: 232.5,
        proteinas: 19.5,
        carbohidratos: 1.65,
        grasas: 16.5,
      },
      {
        alimentoId: "alim-012",
        nombre: "Espinacas frescas",
        cantidad: 100,
        calorias: 23,
        proteinas: 2.9,
        carbohidratos: 3.6,
        grasas: 0.4,
      },
      {
        alimentoId: "alim-015",
        nombre: "Aceite de oliva virgen extra",
        cantidad: 5,
        calorias: 44.2,
        proteinas: 0,
        carbohidratos: 0,
        grasas: 5,
      },
    ],
    instrucciones: [
      "Batir los huevos con una pizca de sal",
      "Calentar el aceite en una sartén antiadherente",
      "Añadir las espinacas y saltear brevemente",
      "Verter los huevos batidos sobre las espinacas",
      "Cocinar a fuego medio hasta que cuaje",
      "Dar la vuelta y cocinar el otro lado",
    ],
    caloriasTotal: 299.7,
    proteinasTotal: 22.4,
    carbohidratosTotal: 5.25,
    grasasTotal: 21.9,
    caloriasPorcion: 299.7,
    proteinasPorcion: 22.4,
    carbohidratosPorcion: 5.25,
    grasasPorcion: 21.9,
    etiquetas: ["alto_proteina", "sin_gluten", "bajo_carbohidrato", "vegetariano"],
    estado: "publicado",
    createdAt: "2024-02-02",
  },
  {
    id: "rec-003",
    nombre: "Overnight oats con plátano y almendras",
    descripcion: "Desayuno rápido y nutritivo que puedes preparar la noche anterior",
    tipoComida: "desayuno",
    tiempoPreparacion: 10,
    porciones: 1,
    dificultad: "facil",
    ingredientes: [
      {
        alimentoId: "alim-006",
        nombre: "Avena en copos",
        cantidad: 50,
        calorias: 194.5,
        proteinas: 8.45,
        carbohidratos: 33,
        grasas: 3.45,
      },
      {
        alimentoId: "alim-009",
        nombre: "Yogur griego natural",
        cantidad: 150,
        calorias: 145.5,
        proteinas: 13.5,
        carbohidratos: 5.4,
        grasas: 7.5,
      },
      {
        alimentoId: "alim-008",
        nombre: "Plátano",
        cantidad: 100,
        calorias: 89,
        proteinas: 1.1,
        carbohidratos: 23,
        grasas: 0.3,
      },
      {
        alimentoId: "alim-010",
        nombre: "Almendras",
        cantidad: 15,
        calorias: 86.85,
        proteinas: 3.15,
        carbohidratos: 3.3,
        grasas: 7.35,
      },
    ],
    instrucciones: [
      "Mezclar la avena con el yogur en un recipiente",
      "Tapar y refrigerar durante la noche",
      "Por la mañana, añadir el plátano en rodajas",
      "Decorar con las almendras troceadas",
      "Opcional: añadir miel o canela al gusto",
    ],
    caloriasTotal: 515.85,
    proteinasTotal: 26.2,
    carbohidratosTotal: 64.7,
    grasasTotal: 18.6,
    caloriasPorcion: 515.85,
    proteinasPorcion: 26.2,
    carbohidratosPorcion: 64.7,
    grasasPorcion: 18.6,
    etiquetas: ["vegetariano", "alto_fibra", "meal_prep"],
    estado: "publicado",
    createdAt: "2024-02-03",
  },
  {
    id: "rec-004",
    nombre: "Salmón al horno con boniato",
    descripcion: "Cena equilibrada rica en omega-3 y carbohidratos complejos",
    tipoComida: "cena",
    tiempoPreparacion: 40,
    porciones: 2,
    dificultad: "media",
    ingredientes: [
      {
        alimentoId: "alim-003",
        nombre: "Salmón atlántico",
        cantidad: 400,
        calorias: 832,
        proteinas: 80,
        carbohidratos: 0,
        grasas: 52,
      },
      {
        alimentoId: "alim-013",
        nombre: "Boniato/Batata",
        cantidad: 300,
        calorias: 258,
        proteinas: 4.8,
        carbohidratos: 60,
        grasas: 0.3,
      },
      {
        alimentoId: "alim-012",
        nombre: "Espinacas frescas",
        cantidad: 100,
        calorias: 23,
        proteinas: 2.9,
        carbohidratos: 3.6,
        grasas: 0.4,
      },
      {
        alimentoId: "alim-015",
        nombre: "Aceite de oliva virgen extra",
        cantidad: 20,
        calorias: 176.8,
        proteinas: 0,
        carbohidratos: 0,
        grasas: 20,
      },
    ],
    instrucciones: [
      "Precalentar el horno a 200°C",
      "Cortar el boniato en rodajas y colocar en bandeja de horno",
      "Rociar con aceite de oliva y hornear 20 minutos",
      "Sazonar el salmón con sal, pimienta y hierbas",
      "Añadir el salmón a la bandeja y hornear 15 minutos más",
      "Servir sobre cama de espinacas frescas",
    ],
    caloriasTotal: 1289.8,
    proteinasTotal: 87.7,
    carbohidratosTotal: 63.6,
    grasasTotal: 72.7,
    caloriasPorcion: 644.9,
    proteinasPorcion: 43.85,
    carbohidratosPorcion: 31.8,
    grasasPorcion: 36.35,
    etiquetas: ["sin_gluten", "omega3", "alto_proteina"],
    estado: "publicado",
    createdAt: "2024-02-05",
  },
  {
    id: "rec-005",
    nombre: "Ensalada de lentejas mediterránea",
    descripcion: "Plato vegano completo rico en proteínas vegetales y fibra",
    tipoComida: "comida",
    tiempoPreparacion: 25,
    porciones: 3,
    dificultad: "facil",
    ingredientes: [
      {
        alimentoId: "alim-011",
        nombre: "Lentejas cocidas",
        cantidad: 400,
        calorias: 464,
        proteinas: 36,
        carbohidratos: 80,
        grasas: 1.6,
      },
      {
        alimentoId: "alim-007",
        nombre: "Aguacate",
        cantidad: 150,
        calorias: 240,
        proteinas: 3,
        carbohidratos: 13.5,
        grasas: 22.5,
      },
      {
        alimentoId: "alim-012",
        nombre: "Espinacas frescas",
        cantidad: 100,
        calorias: 23,
        proteinas: 2.9,
        carbohidratos: 3.6,
        grasas: 0.4,
      },
      {
        alimentoId: "alim-015",
        nombre: "Aceite de oliva virgen extra",
        cantidad: 30,
        calorias: 265.2,
        proteinas: 0,
        carbohidratos: 0,
        grasas: 30,
      },
    ],
    instrucciones: [
      "Escurrir y enjuagar las lentejas",
      "Cortar el aguacate en cubos",
      "Mezclar las lentejas con las espinacas",
      "Añadir el aguacate",
      "Aliñar con aceite de oliva, limón, sal y pimienta",
      "Servir frío o a temperatura ambiente",
    ],
    caloriasTotal: 992.2,
    proteinasTotal: 41.9,
    carbohidratosTotal: 97.1,
    grasasTotal: 54.5,
    caloriasPorcion: 330.73,
    proteinasPorcion: 13.97,
    carbohidratosPorcion: 32.37,
    grasasPorcion: 18.17,
    etiquetas: ["vegano", "sin_gluten", "alto_fibra"],
    estado: "publicado",
    createdAt: "2024-02-06",
  },
  {
    id: "rec-006",
    nombre: "Smoothie proteico de plátano",
    descripcion: "Batido perfecto como snack pre o post entrenamiento",
    tipoComida: "snack",
    tiempoPreparacion: 5,
    porciones: 1,
    dificultad: "facil",
    ingredientes: [
      {
        alimentoId: "alim-008",
        nombre: "Plátano",
        cantidad: 120,
        calorias: 106.8,
        proteinas: 1.32,
        carbohidratos: 27.6,
        grasas: 0.36,
      },
      {
        alimentoId: "alim-009",
        nombre: "Yogur griego natural",
        cantidad: 200,
        calorias: 194,
        proteinas: 18,
        carbohidratos: 7.2,
        grasas: 10,
      },
      {
        alimentoId: "alim-010",
        nombre: "Almendras",
        cantidad: 20,
        calorias: 115.8,
        proteinas: 4.2,
        carbohidratos: 4.4,
        grasas: 9.8,
      },
      {
        alimentoId: "alim-006",
        nombre: "Avena en copos",
        cantidad: 20,
        calorias: 77.8,
        proteinas: 3.38,
        carbohidratos: 13.2,
        grasas: 1.38,
      },
    ],
    instrucciones: [
      "Añadir todos los ingredientes a la batidora",
      "Añadir 100ml de agua o leche",
      "Batir hasta conseguir textura homogénea",
      "Servir inmediatamente",
    ],
    caloriasTotal: 494.4,
    proteinasTotal: 26.9,
    carbohidratosTotal: 52.4,
    grasasTotal: 21.54,
    caloriasPorcion: 494.4,
    proteinasPorcion: 26.9,
    carbohidratosPorcion: 52.4,
    grasasPorcion: 21.54,
    etiquetas: ["vegetariano", "pre_entreno", "rapido"],
    estado: "publicado",
    createdAt: "2024-02-07",
  },
  {
    id: "rec-007",
    nombre: "Wrap de atún y aguacate",
    descripcion: "Almuerzo rápido y portátil, ideal para llevar",
    tipoComida: "almuerzo",
    tiempoPreparacion: 10,
    porciones: 1,
    dificultad: "facil",
    ingredientes: [
      {
        alimentoId: "alim-014",
        nombre: "Atún en conserva al natural",
        cantidad: 100,
        calorias: 116,
        proteinas: 26,
        carbohidratos: 0,
        grasas: 1,
      },
      {
        alimentoId: "alim-007",
        nombre: "Aguacate",
        cantidad: 80,
        calorias: 128,
        proteinas: 1.6,
        carbohidratos: 7.2,
        grasas: 12,
      },
      {
        alimentoId: "alim-012",
        nombre: "Espinacas frescas",
        cantidad: 30,
        calorias: 6.9,
        proteinas: 0.87,
        carbohidratos: 1.08,
        grasas: 0.12,
      },
    ],
    instrucciones: [
      "Escurrir bien el atún",
      "Machacar el aguacate con un tenedor",
      "Mezclar el atún con el aguacate",
      "Extender sobre una tortilla o pan wrap",
      "Añadir las espinacas",
      "Enrollar y cortar por la mitad",
    ],
    caloriasTotal: 250.9,
    proteinasTotal: 28.47,
    carbohidratosTotal: 8.28,
    grasasTotal: 13.12,
    caloriasPorcion: 250.9,
    proteinasPorcion: 28.47,
    carbohidratosPorcion: 8.28,
    grasasPorcion: 13.12,
    etiquetas: ["sin_gluten", "alto_proteina", "rapido", "para_llevar"],
    estado: "publicado",
    createdAt: "2024-02-08",
  },
  {
    id: "rec-008",
    nombre: "Buddha bowl vegano",
    descripcion: "Bowl completo 100% vegetal con todos los nutrientes",
    tipoComida: "comida",
    tiempoPreparacion: 30,
    porciones: 2,
    dificultad: "media",
    ingredientes: [
      {
        alimentoId: "alim-011",
        nombre: "Lentejas cocidas",
        cantidad: 300,
        calorias: 348,
        proteinas: 27,
        carbohidratos: 60,
        grasas: 1.2,
      },
      {
        alimentoId: "alim-013",
        nombre: "Boniato/Batata",
        cantidad: 200,
        calorias: 172,
        proteinas: 3.2,
        carbohidratos: 40,
        grasas: 0.2,
      },
      {
        alimentoId: "alim-004",
        nombre: "Brócoli",
        cantidad: 150,
        calorias: 51,
        proteinas: 4.2,
        carbohidratos: 10.5,
        grasas: 0.6,
      },
      {
        alimentoId: "alim-007",
        nombre: "Aguacate",
        cantidad: 100,
        calorias: 160,
        proteinas: 2,
        carbohidratos: 9,
        grasas: 15,
      },
      {
        alimentoId: "alim-015",
        nombre: "Aceite de oliva virgen extra",
        cantidad: 20,
        calorias: 176.8,
        proteinas: 0,
        carbohidratos: 0,
        grasas: 20,
      },
    ],
    instrucciones: [
      "Asar el boniato en cubos a 200°C por 25 minutos",
      "Cocinar el brócoli al vapor",
      "Calentar las lentejas",
      "Montar los bowls con todos los ingredientes",
      "Añadir aguacate en láminas",
      "Aliñar con aceite de oliva y semillas al gusto",
    ],
    caloriasTotal: 907.8,
    proteinasTotal: 36.4,
    carbohidratosTotal: 119.5,
    grasasTotal: 37,
    caloriasPorcion: 453.9,
    proteinasPorcion: 18.2,
    carbohidratosPorcion: 59.75,
    grasasPorcion: 18.5,
    etiquetas: ["vegano", "sin_gluten", "alto_fibra", "completo"],
    estado: "publicado",
    createdAt: "2024-02-10",
  },
  {
    id: "rec-009",
    nombre: "Tostada de aguacate con huevo",
    descripcion: "Clásico desayuno equilibrado y delicioso",
    tipoComida: "desayuno",
    tiempoPreparacion: 12,
    porciones: 1,
    dificultad: "facil",
    ingredientes: [
      {
        alimentoId: "alim-005",
        nombre: "Huevo entero",
        cantidad: 100,
        calorias: 155,
        proteinas: 13,
        carbohidratos: 1.1,
        grasas: 11,
      },
      {
        alimentoId: "alim-007",
        nombre: "Aguacate",
        cantidad: 80,
        calorias: 128,
        proteinas: 1.6,
        carbohidratos: 7.2,
        grasas: 12,
      },
    ],
    instrucciones: [
      "Tostar el pan",
      "Machacar el aguacate y extender sobre el pan",
      "Cocinar el huevo al gusto (poché, revuelto o frito)",
      "Colocar el huevo sobre el aguacate",
      "Sazonar con sal, pimienta y semillas",
    ],
    caloriasTotal: 283,
    proteinasTotal: 14.6,
    carbohidratosTotal: 8.3,
    grasasTotal: 23,
    caloriasPorcion: 283,
    proteinasPorcion: 14.6,
    carbohidratosPorcion: 8.3,
    grasasPorcion: 23,
    etiquetas: ["vegetariano", "sin_gluten", "rapido"],
    estado: "publicado",
    createdAt: "2024-02-11",
  },
  {
    id: "rec-010",
    nombre: "Bol de quinoa con verduras",
    descripcion: "Comida completa vegana en borrador para revisión",
    tipoComida: "comida",
    tiempoPreparacion: 35,
    porciones: 2,
    dificultad: "media",
    ingredientes: [
      {
        alimentoId: "alim-004",
        nombre: "Brócoli",
        cantidad: 200,
        calorias: 68,
        proteinas: 5.6,
        carbohidratos: 14,
        grasas: 0.8,
      },
      {
        alimentoId: "alim-012",
        nombre: "Espinacas frescas",
        cantidad: 100,
        calorias: 23,
        proteinas: 2.9,
        carbohidratos: 3.6,
        grasas: 0.4,
      },
      {
        alimentoId: "alim-010",
        nombre: "Almendras",
        cantidad: 30,
        calorias: 173.7,
        proteinas: 6.3,
        carbohidratos: 6.6,
        grasas: 14.7,
      },
    ],
    instrucciones: [
      "Cocinar la quinoa según instrucciones",
      "Saltear las verduras",
      "Mezclar todo en un bol",
      "Decorar con almendras",
    ],
    caloriasTotal: 264.7,
    proteinasTotal: 14.8,
    carbohidratosTotal: 24.2,
    grasasTotal: 15.9,
    caloriasPorcion: 132.35,
    proteinasPorcion: 7.4,
    carbohidratosPorcion: 12.1,
    grasasPorcion: 7.95,
    etiquetas: ["vegano", "sin_gluten"],
    estado: "borrador",
    createdAt: "2024-02-12",
  },
];

// ============================================
// MENÚS ESTÁTICOS
// ============================================

export const menusData: MenuSemanal[] = [
  {
    id: "menu-001",
    nombre: "Plan de definición - Semana 1",
    clienteId: "cliente-001",
    clienteNombre: "María García",
    objetivo: "definicion",
    restricciones: ["sin_gluten"],
    dias: [
      {
        dia: "lunes",
        comidas: [
          {
            id: "com-001",
            tipoComida: "desayuno",
            hora: "08:00",
            usaReceta: true,
            recetaId: "rec-002",
            recetaNombre: "Tortilla de claras con espinacas",
            porciones: 1,
            calorias: 299.7,
            proteinas: 22.4,
            carbohidratos: 5.25,
            grasas: 21.9,
            activo: true,
          },
          {
            id: "com-002",
            tipoComida: "comida",
            hora: "14:00",
            usaReceta: true,
            recetaId: "rec-001",
            recetaNombre: "Bowl de pollo con arroz integral",
            porciones: 1,
            calorias: 619.3,
            proteinas: 54.93,
            carbohidratos: 64,
            grasas: 15.33,
            activo: true,
          },
          {
            id: "com-003",
            tipoComida: "merienda",
            hora: "17:00",
            usaReceta: true,
            recetaId: "rec-006",
            recetaNombre: "Smoothie proteico de plátano",
            porciones: 1,
            calorias: 494.4,
            proteinas: 26.9,
            carbohidratos: 52.4,
            grasas: 21.54,
            activo: true,
          },
          {
            id: "com-004",
            tipoComida: "cena",
            hora: "21:00",
            usaReceta: true,
            recetaId: "rec-004",
            recetaNombre: "Salmón al horno con boniato",
            porciones: 1,
            calorias: 644.9,
            proteinas: 43.85,
            carbohidratos: 31.8,
            grasas: 36.35,
            activo: true,
          },
        ],
        caloriasTotal: 2058.3,
        proteinasTotal: 148.08,
        carbohidratosTotal: 153.45,
        grasasTotal: 95.12,
      },
    ],
    caloriasDiarias: 2058.3,
    proteinasDiarias: 148.08,
    carbohidratosDiarios: 153.45,
    grasasDiarias: 95.12,
    estado: "activo",
    fechaInicio: "2024-02-12",
    fechaFin: "2024-02-18",
    createdAt: "2024-02-11",
  },
  {
    id: "menu-002",
    nombre: "Plan vegano - Ganancia muscular",
    clienteId: "cliente-002",
    clienteNombre: "Carlos López",
    objetivo: "ganancia_muscular",
    restricciones: ["vegano", "sin_gluten"],
    dias: [
      {
        dia: "lunes",
        comidas: [
          {
            id: "com-005",
            tipoComida: "desayuno",
            hora: "07:30",
            usaReceta: true,
            recetaId: "rec-003",
            recetaNombre: "Overnight oats con plátano y almendras",
            porciones: 1.5,
            calorias: 773.78,
            proteinas: 39.3,
            carbohidratos: 97.05,
            grasas: 27.9,
            activo: true,
          },
          {
            id: "com-006",
            tipoComida: "comida",
            hora: "13:00",
            usaReceta: true,
            recetaId: "rec-008",
            recetaNombre: "Buddha bowl vegano",
            porciones: 1.5,
            calorias: 680.85,
            proteinas: 27.3,
            carbohidratos: 89.63,
            grasas: 27.75,
            activo: true,
          },
          {
            id: "com-007",
            tipoComida: "cena",
            hora: "20:00",
            usaReceta: true,
            recetaId: "rec-005",
            recetaNombre: "Ensalada de lentejas mediterránea",
            porciones: 2,
            calorias: 661.47,
            proteinas: 27.93,
            carbohidratos: 64.73,
            grasas: 36.33,
            activo: true,
          },
        ],
        caloriasTotal: 2116.1,
        proteinasTotal: 94.53,
        carbohidratosTotal: 251.41,
        grasasTotal: 91.98,
      },
    ],
    caloriasDiarias: 2116.1,
    proteinasDiarias: 94.53,
    carbohidratosDiarios: 251.41,
    grasasDiarias: 91.98,
    estado: "activo",
    fechaInicio: "2024-02-19",
    fechaFin: "2024-02-25",
    createdAt: "2024-02-18",
  },
  {
    id: "menu-003",
    nombre: "Plan de pérdida de peso",
    clienteId: "cliente-003",
    clienteNombre: "Ana Martínez",
    objetivo: "perdida_peso",
    restricciones: [],
    dias: [],
    caloriasDiarias: 1500,
    proteinasDiarias: 120,
    carbohidratosDiarios: 100,
    grasasDiarias: 50,
    estado: "borrador",
    createdAt: "2024-02-20",
  },
];

// ============================================
// SUSTITUCIONES ESTÁTICAS
// ============================================

export const sustitucionesData: Sustitucion[] = [
  {
    id: "sust-001",
    alimentoOriginalId: "alim-001",
    alimentoOriginalNombre: "Pechuga de pollo",
    alimentoSustitutoId: "alim-014",
    alimentoSustitutoNombre: "Atún en conserva al natural",
    factorConversion: 1.0,
    restriccion: "variedad",
    notas: "Misma cantidad de proteína, menos grasa",
    activo: true,
  },
  {
    id: "sust-002",
    alimentoOriginalId: "alim-001",
    alimentoOriginalNombre: "Pechuga de pollo",
    alimentoSustitutoId: "alim-011",
    alimentoSustitutoNombre: "Lentejas cocidas",
    factorConversion: 3.0,
    restriccion: "vegano",
    notas: "Necesitas 3x más lentejas para igualar proteínas",
    activo: true,
  },
  {
    id: "sust-003",
    alimentoOriginalId: "alim-009",
    alimentoOriginalNombre: "Yogur griego natural",
    alimentoSustitutoId: "alim-007",
    alimentoSustitutoNombre: "Aguacate",
    factorConversion: 1.5,
    restriccion: "vegano",
    notas: "Para bowls y smoothies veganos",
    activo: true,
  },
  {
    id: "sust-004",
    alimentoOriginalId: "alim-002",
    alimentoOriginalNombre: "Arroz integral",
    alimentoSustitutoId: "alim-013",
    alimentoSustitutoNombre: "Boniato/Batata",
    factorConversion: 2.5,
    restriccion: "variedad",
    notas: "Alternativa con más fibra y menos calorías",
    activo: true,
  },
  {
    id: "sust-005",
    alimentoOriginalId: "alim-005",
    alimentoOriginalNombre: "Huevo entero",
    alimentoSustitutoId: "alim-011",
    alimentoSustitutoNombre: "Lentejas cocidas",
    factorConversion: 2.0,
    restriccion: "vegano",
    notas: "Sustitución para tortillas y revueltos veganos",
    activo: true,
  },
  {
    id: "sust-006",
    alimentoOriginalId: "alim-006",
    alimentoOriginalNombre: "Avena en copos",
    alimentoSustitutoId: "alim-002",
    alimentoSustitutoNombre: "Arroz integral",
    factorConversion: 1.0,
    restriccion: "sin_gluten",
    notas: "Para personas con intolerancia al gluten (verificar avena certificada)",
    activo: true,
  },
];

// ============================================
// RESTRICCIONES ESTÁTICAS
// ============================================

export const restriccionesData: Restriccion[] = [
  {
    id: "rest-001",
    nombre: "Vegano",
    codigo: "vegano",
    descripcion: "Excluye todos los productos de origen animal",
    color: "bg-green-500",
    icono: "🌱",
    alimentosExcluidos: ["proteinas", "lacteos", "huevos"],
    activo: true,
  },
  {
    id: "rest-002",
    nombre: "Vegetariano",
    codigo: "vegetariano",
    descripcion: "Excluye carne y pescado, permite lácteos y huevos",
    color: "bg-emerald-500",
    icono: "🥬",
    alimentosExcluidos: ["carnes", "pescados"],
    activo: true,
  },
  {
    id: "rest-003",
    nombre: "Sin Gluten",
    codigo: "sin_gluten",
    descripcion: "Excluye alimentos que contienen gluten",
    color: "bg-amber-500",
    icono: "🌾",
    alimentosExcluidos: ["trigo", "cebada", "centeno", "avena"],
    activo: true,
  },
  {
    id: "rest-004",
    nombre: "Sin Lactosa",
    codigo: "sin_lactosa",
    descripcion: "Excluye productos lácteos con lactosa",
    color: "bg-blue-500",
    icono: "🥛",
    alimentosExcluidos: ["lacteos"],
    activo: true,
  },
  {
    id: "rest-005",
    nombre: "Bajo en Carbohidratos",
    codigo: "bajo_carbohidrato",
    descripcion: "Limita el consumo de carbohidratos a menos de 100g diarios",
    color: "bg-orange-500",
    icono: "🍞",
    alimentosExcluidos: [],
    activo: true,
  },
  {
    id: "rest-006",
    nombre: "Alto en Proteína",
    codigo: "alto_proteina",
    descripcion: "Prioriza alimentos ricos en proteínas",
    color: "bg-red-500",
    icono: "💪",
    alimentosExcluidos: [],
    activo: true,
  },
  {
    id: "rest-007",
    nombre: "Sin Frutos Secos",
    codigo: "sin_frutos_secos",
    descripcion: "Excluye todos los frutos secos por alergia",
    color: "bg-purple-500",
    icono: "🥜",
    alimentosExcluidos: ["frutos_secos"],
    activo: true,
  },
  {
    id: "rest-008",
    nombre: "Sin Mariscos",
    codigo: "sin_mariscos",
    descripcion: "Excluye mariscos y crustáceos",
    color: "bg-cyan-500",
    icono: "🦐",
    alimentosExcluidos: ["mariscos"],
    activo: true,
  },
];

// ============================================
// ESTADÍSTICAS CALCULADAS
// ============================================

export const getDietaStats = (): DietaStats => {
  const alimentosManuales = alimentosData.filter((a) => a.origen === "manual").length;
  const alimentosApi = alimentosData.filter((a) => a.origen !== "manual").length;
  const recetasPublicadas = recetasData.filter((r) => r.estado === "publicado").length;
  const recetasBorrador = recetasData.filter((r) => r.estado === "borrador").length;
  const menusActivos = menusData.filter((m) => m.estado === "activo").length;

  return {
    totalAlimentos: alimentosData.length,
    alimentosManuales,
    alimentosApi,
    totalRecetas: recetasData.length,
    recetasPublicadas,
    recetasBorrador,
    totalMenus: menusData.length,
    menusActivos,
    totalSustituciones: sustitucionesData.length,
    totalRestricciones: restriccionesData.filter((r) => r.activo).length,
  };
};

// ============================================
// OPCIONES PARA FILTROS Y SELECT
// ============================================

export const categoriasAlimentos = [
  { value: "proteinas", label: "Proteínas" },
  { value: "carbohidratos", label: "Carbohidratos" },
  { value: "grasas", label: "Grasas" },
  { value: "verduras", label: "Verduras" },
  { value: "frutas", label: "Frutas" },
  { value: "lacteos", label: "Lácteos" },
  { value: "legumbres", label: "Legumbres" },
  { value: "frutos_secos", label: "Frutos Secos" },
  { value: "otros", label: "Otros" },
];

export const tiposComida = [
  { value: "desayuno", label: "Desayuno" },
  { value: "almuerzo", label: "Almuerzo" },
  { value: "comida", label: "Comida" },
  { value: "merienda", label: "Merienda" },
  { value: "cena", label: "Cena" },
  { value: "snack", label: "Snack" },
];

export const etiquetasComunes = [
  { value: "vegano", label: "Vegano" },
  { value: "vegetariano", label: "Vegetariano" },
  { value: "sin_gluten", label: "Sin Gluten" },
  { value: "sin_lactosa", label: "Sin Lactosa" },
  { value: "alto_proteina", label: "Alto en Proteína" },
  { value: "bajo_calorias", label: "Bajo en Calorías" },
  { value: "bajo_carbohidrato", label: "Bajo en Carbohidratos" },
  { value: "alto_fibra", label: "Alto en Fibra" },
  { value: "grasas_saludables", label: "Grasas Saludables" },
  { value: "omega3", label: "Rico en Omega-3" },
  { value: "rapido", label: "Rápido" },
  { value: "meal_prep", label: "Meal Prep" },
  { value: "post_entreno", label: "Post Entreno" },
  { value: "pre_entreno", label: "Pre Entreno" },
  { value: "para_llevar", label: "Para Llevar" },
];

export const origenesAlimentos = [
  { value: "manual", label: "Manual" },
  { value: "open_food_facts", label: "Open Food Facts" },
  { value: "bedca", label: "BEDCA" },
];

export const estadosReceta = [
  { value: "borrador", label: "Borrador" },
  { value: "publicado", label: "Publicado" },
  { value: "archivado", label: "Archivado" },
];

export const objetivosMenu = [
  { value: "perdida_peso", label: "Pérdida de Peso" },
  { value: "ganancia_muscular", label: "Ganancia Muscular" },
  { value: "mantenimiento", label: "Mantenimiento" },
  { value: "definicion", label: "Definición" },
  { value: "otro", label: "Otro" },
];
