import { Receta } from "./schema";

// ============================================
// RECETAS ESTÁTICAS
// ============================================

export const recetasData: Receta[] = [
  {
    id: "rec-001",
    nombre: "Bowl de pollo con arroz integral",
    descripcion: "Un bowl nutritivo y equilibrado, perfecto para después del entrenamiento",
    tipoComida: "comida",
    tiempoPreparacion: 35,
    porciones: 2,
    dificultad: "facil",
    ingredientes: [
      {
        alimentoId: "alim-001",
        nombre: "Pechuga de pollo",
        cantidad: 300,
        calorias: 495,
        proteinas: 93,
        carbohidratos: 0,
        grasas: 10.8,
      },
      {
        alimentoId: "alim-002",
        nombre: "Arroz integral",
        cantidad: 150,
        calorias: 543,
        proteinas: 11.25,
        carbohidratos: 114,
        grasas: 4.05,
      },
      {
        alimentoId: "alim-004",
        nombre: "Brócoli",
        cantidad: 200,
        calorias: 68,
        proteinas: 5.6,
        carbohidratos: 14,
        grasas: 0.8,
      },
      {
        alimentoId: "alim-015",
        nombre: "Aceite de oliva virgen extra",
        cantidad: 15,
        calorias: 132.6,
        proteinas: 0,
        carbohidratos: 0,
        grasas: 15,
      },
    ],
    instrucciones: [
      "Cocinar el arroz integral según las instrucciones del paquete",
      "Cortar la pechuga de pollo en tiras y sazonar con sal, pimienta y especias al gusto",
      "Cocinar el pollo a la plancha con un poco de aceite de oliva",
      "Cocinar el brócoli al vapor durante 5-7 minutos",
      "Montar el bowl con arroz, pollo y brócoli",
      "Aliñar con el resto del aceite de oliva",
    ],
    caloriasTotal: 1238.6,
    proteinasTotal: 109.85,
    carbohidratosTotal: 128,
    grasasTotal: 30.65,
    caloriasPorcion: 619.3,
    proteinasPorcion: 54.93,
    carbohidratosPorcion: 64,
    grasasPorcion: 15.33,
    etiquetas: ["alto_proteina", "sin_gluten", "post_entreno"],
    estado: "publicado",
    createdAt: "2024-02-01",
  },
  {
    id: "rec-002",
    nombre: "Tortilla de claras con espinacas",
    descripcion: "Desayuno rico en proteínas y bajo en calorías",
    tipoComida: "desayuno",
    tiempoPreparacion: 15,
    porciones: 1,
    dificultad: "facil",
    ingredientes: [
      {
        alimentoId: "alim-005",
        nombre: "Huevo entero",
        cantidad: 150,
        calorias: 232.5,
        proteinas: 19.5,
        carbohidratos: 1.65,
        grasas: 16.5,
      },
      {
        alimentoId: "alim-012",
        nombre: "Espinacas frescas",
        cantidad: 100,
        calorias: 23,
        proteinas: 2.9,
        carbohidratos: 3.6,
        grasas: 0.4,
      },
      {
        alimentoId: "alim-015",
        nombre: "Aceite de oliva virgen extra",
        cantidad: 5,
        calorias: 44.2,
        proteinas: 0,
        carbohidratos: 0,
        grasas: 5,
      },
    ],
    instrucciones: [
      "Batir los huevos con una pizca de sal",
      "Calentar el aceite en una sartén antiadherente",
      "Añadir las espinacas y saltear brevemente",
      "Verter los huevos batidos sobre las espinacas",
      "Cocinar a fuego medio hasta que cuaje",
      "Dar la vuelta y cocinar el otro lado",
    ],
    caloriasTotal: 299.7,
    proteinasTotal: 22.4,
    carbohidratosTotal: 5.25,
    grasasTotal: 21.9,
    caloriasPorcion: 299.7,
    proteinasPorcion: 22.4,
    carbohidratosPorcion: 5.25,
    grasasPorcion: 21.9,
    etiquetas: ["alto_proteina", "sin_gluten", "bajo_carbohidrato", "vegetariano"],
    estado: "publicado",
    createdAt: "2024-02-02",
  },
  {
    id: "rec-003",
    nombre: "Overnight oats con plátano y almendras",
    descripcion: "Desayuno rápido y nutritivo que puedes preparar la noche anterior",
    tipoComida: "desayuno",
    tiempoPreparacion: 10,
    porciones: 1,
    dificultad: "facil",
    ingredientes: [
      {
        alimentoId: "alim-006",
        nombre: "Avena en copos",
        cantidad: 50,
        calorias: 194.5,
        proteinas: 8.45,
        carbohidratos: 33,
        grasas: 3.45,
      },
      {
        alimentoId: "alim-009",
        nombre: "Yogur griego natural",
        cantidad: 150,
        calorias: 145.5,
        proteinas: 13.5,
        carbohidratos: 5.4,
        grasas: 7.5,
      },
      {
        alimentoId: "alim-008",
        nombre: "Plátano",
        cantidad: 100,
        calorias: 89,
        proteinas: 1.1,
        carbohidratos: 23,
        grasas: 0.3,
      },
      {
        alimentoId: "alim-010",
        nombre: "Almendras",
        cantidad: 15,
        calorias: 86.85,
        proteinas: 3.15,
        carbohidratos: 3.3,
        grasas: 7.35,
      },
    ],
    instrucciones: [
      "Mezclar la avena con el yogur en un recipiente",
      "Tapar y refrigerar durante la noche",
      "Por la mañana, añadir el plátano en rodajas",
      "Decorar con las almendras troceadas",
      "Opcional: añadir miel o canela al gusto",
    ],
    caloriasTotal: 515.85,
    proteinasTotal: 26.2,
    carbohidratosTotal: 64.7,
    grasasTotal: 18.6,
    caloriasPorcion: 515.85,
    proteinasPorcion: 26.2,
    carbohidratosPorcion: 64.7,
    grasasPorcion: 18.6,
    etiquetas: ["vegetariano", "alto_fibra", "meal_prep"],
    estado: "publicado",
    createdAt: "2024-02-03",
  },
  {
    id: "rec-004",
    nombre: "Salmón al horno con boniato",
    descripcion: "Cena equilibrada rica en omega-3 y carbohidratos complejos",
    tipoComida: "cena",
    tiempoPreparacion: 40,
    porciones: 2,
    dificultad: "media",
    ingredientes: [
      {
        alimentoId: "alim-003",
        nombre: "Salmón atlántico",
        cantidad: 400,
        calorias: 832,
        proteinas: 80,
        carbohidratos: 0,
        grasas: 52,
      },
      {
        alimentoId: "alim-013",
        nombre: "Boniato/Batata",
        cantidad: 300,
        calorias: 258,
        proteinas: 4.8,
        carbohidratos: 60,
        grasas: 0.3,
      },
      {
        alimentoId: "alim-012",
        nombre: "Espinacas frescas",
        cantidad: 100,
        calorias: 23,
        proteinas: 2.9,
        carbohidratos: 3.6,
        grasas: 0.4,
      },
      {
        alimentoId: "alim-015",
        nombre: "Aceite de oliva virgen extra",
        cantidad: 20,
        calorias: 176.8,
        proteinas: 0,
        carbohidratos: 0,
        grasas: 20,
      },
    ],
    instrucciones: [
      "Precalentar el horno a 200°C",
      "Cortar el boniato en rodajas y colocar en bandeja de horno",
      "Rociar con aceite de oliva y hornear 20 minutos",
      "Sazonar el salmón con sal, pimienta y hierbas",
      "Añadir el salmón a la bandeja y hornear 15 minutos más",
      "Servir sobre cama de espinacas frescas",
    ],
    caloriasTotal: 1289.8,
    proteinasTotal: 87.7,
    carbohidratosTotal: 63.6,
    grasasTotal: 72.7,
    caloriasPorcion: 644.9,
    proteinasPorcion: 43.85,
    carbohidratosPorcion: 31.8,
    grasasPorcion: 36.35,
    etiquetas: ["sin_gluten", "omega3", "alto_proteina"],
    estado: "publicado",
    createdAt: "2024-02-05",
  },
  {
    id: "rec-005",
    nombre: "Ensalada de lentejas mediterránea",
    descripcion: "Plato vegano completo rico en proteínas vegetales y fibra",
    tipoComida: "comida",
    tiempoPreparacion: 25,
    porciones: 3,
    dificultad: "facil",
    ingredientes: [
      {
        alimentoId: "alim-011",
        nombre: "Lentejas cocidas",
        cantidad: 400,
        calorias: 464,
        proteinas: 36,
        carbohidratos: 80,
        grasas: 1.6,
      },
      {
        alimentoId: "alim-007",
        nombre: "Aguacate",
        cantidad: 150,
        calorias: 240,
        proteinas: 3,
        carbohidratos: 13.5,
        grasas: 22.5,
      },
      {
        alimentoId: "alim-012",
        nombre: "Espinacas frescas",
        cantidad: 100,
        calorias: 23,
        proteinas: 2.9,
        carbohidratos: 3.6,
        grasas: 0.4,
      },
      {
        alimentoId: "alim-015",
        nombre: "Aceite de oliva virgen extra",
        cantidad: 30,
        calorias: 265.2,
        proteinas: 0,
        carbohidratos: 0,
        grasas: 30,
      },
    ],
    instrucciones: [
      "Escurrir y enjuagar las lentejas",
      "Cortar el aguacate en cubos",
      "Mezclar las lentejas con las espinacas",
      "Añadir el aguacate",
      "Aliñar con aceite de oliva, limón, sal y pimienta",
      "Servir frío o a temperatura ambiente",
    ],
    caloriasTotal: 992.2,
    proteinasTotal: 41.9,
    carbohidratosTotal: 97.1,
    grasasTotal: 54.5,
    caloriasPorcion: 330.73,
    proteinasPorcion: 13.97,
    carbohidratosPorcion: 32.37,
    grasasPorcion: 18.17,
    etiquetas: ["vegano", "sin_gluten", "alto_fibra"],
    estado: "publicado",
    createdAt: "2024-02-06",
  },
  {
    id: "rec-006",
    nombre: "Smoothie proteico de plátano",
    descripcion: "Batido perfecto como snack pre o post entrenamiento",
    tipoComida: "snack",
    tiempoPreparacion: 5,
    porciones: 1,
    dificultad: "facil",
    ingredientes: [
      {
        alimentoId: "alim-008",
        nombre: "Plátano",
        cantidad: 120,
        calorias: 106.8,
        proteinas: 1.32,
        carbohidratos: 27.6,
        grasas: 0.36,
      },
      {
        alimentoId: "alim-009",
        nombre: "Yogur griego natural",
        cantidad: 200,
        calorias: 194,
        proteinas: 18,
        carbohidratos: 7.2,
        grasas: 10,
      },
      {
        alimentoId: "alim-010",
        nombre: "Almendras",
        cantidad: 20,
        calorias: 115.8,
        proteinas: 4.2,
        carbohidratos: 4.4,
        grasas: 9.8,
      },
      {
        alimentoId: "alim-006",
        nombre: "Avena en copos",
        cantidad: 20,
        calorias: 77.8,
        proteinas: 3.38,
        carbohidratos: 13.2,
        grasas: 1.38,
      },
    ],
    instrucciones: [
      "Añadir todos los ingredientes a la batidora",
      "Añadir 100ml de agua o leche",
      "Batir hasta conseguir textura homogénea",
      "Servir inmediatamente",
    ],
    caloriasTotal: 494.4,
    proteinasTotal: 26.9,
    carbohidratosTotal: 52.4,
    grasasTotal: 21.54,
    caloriasPorcion: 494.4,
    proteinasPorcion: 26.9,
    carbohidratosPorcion: 52.4,
    grasasPorcion: 21.54,
    etiquetas: ["vegetariano", "pre_entreno", "rapido"],
    estado: "publicado",
    createdAt: "2024-02-07",
  },
  {
    id: "rec-007",
    nombre: "Wrap de atún y aguacate",
    descripcion: "Almuerzo rápido y portátil, ideal para llevar",
    tipoComida: "almuerzo",
    tiempoPreparacion: 10,
    porciones: 1,
    dificultad: "facil",
    ingredientes: [
      {
        alimentoId: "alim-014",
        nombre: "Atún en conserva al natural",
        cantidad: 100,
        calorias: 116,
        proteinas: 26,
        carbohidratos: 0,
        grasas: 1,
      },
      {
        alimentoId: "alim-007",
        nombre: "Aguacate",
        cantidad: 80,
        calorias: 128,
        proteinas: 1.6,
        carbohidratos: 7.2,
        grasas: 12,
      },
      {
        alimentoId: "alim-012",
        nombre: "Espinacas frescas",
        cantidad: 30,
        calorias: 6.9,
        proteinas: 0.87,
        carbohidratos: 1.08,
        grasas: 0.12,
      },
    ],
    instrucciones: [
      "Escurrir bien el atún",
      "Machacar el aguacate con un tenedor",
      "Mezclar el atún con el aguacate",
      "Extender sobre una tortilla o pan wrap",
      "Añadir las espinacas",
      "Enrollar y cortar por la mitad",
    ],
    caloriasTotal: 250.9,
    proteinasTotal: 28.47,
    carbohidratosTotal: 8.28,
    grasasTotal: 13.12,
    caloriasPorcion: 250.9,
    proteinasPorcion: 28.47,
    carbohidratosPorcion: 8.28,
    grasasPorcion: 13.12,
    etiquetas: ["sin_gluten", "alto_proteina", "rapido", "para_llevar"],
    estado: "publicado",
    createdAt: "2024-02-08",
  },
  {
    id: "rec-008",
    nombre: "Buddha bowl vegano",
    descripcion: "Bowl completo 100% vegetal con todos los nutrientes",
    tipoComida: "comida",
    tiempoPreparacion: 30,
    porciones: 2,
    dificultad: "media",
    ingredientes: [
      {
        alimentoId: "alim-011",
        nombre: "Lentejas cocidas",
        cantidad: 300,
        calorias: 348,
        proteinas: 27,
        carbohidratos: 60,
        grasas: 1.2,
      },
      {
        alimentoId: "alim-013",
        nombre: "Boniato/Batata",
        cantidad: 200,
        calorias: 172,
        proteinas: 3.2,
        carbohidratos: 40,
        grasas: 0.2,
      },
      {
        alimentoId: "alim-004",
        nombre: "Brócoli",
        cantidad: 150,
        calorias: 51,
        proteinas: 4.2,
        carbohidratos: 10.5,
        grasas: 0.6,
      },
      {
        alimentoId: "alim-007",
        nombre: "Aguacate",
        cantidad: 100,
        calorias: 160,
        proteinas: 2,
        carbohidratos: 9,
        grasas: 15,
      },
      {
        alimentoId: "alim-015",
        nombre: "Aceite de oliva virgen extra",
        cantidad: 20,
        calorias: 176.8,
        proteinas: 0,
        carbohidratos: 0,
        grasas: 20,
      },
    ],
    instrucciones: [
      "Asar el boniato en cubos a 200°C por 25 minutos",
      "Cocinar el brócoli al vapor",
      "Calentar las lentejas",
      "Montar los bowls con todos los ingredientes",
      "Añadir aguacate en láminas",
      "Aliñar con aceite de oliva y semillas al gusto",
    ],
    caloriasTotal: 907.8,
    proteinasTotal: 36.4,
    carbohidratosTotal: 119.5,
    grasasTotal: 37,
    caloriasPorcion: 453.9,
    proteinasPorcion: 18.2,
    carbohidratosPorcion: 59.75,
    grasasPorcion: 18.5,
    etiquetas: ["vegano", "sin_gluten", "alto_fibra", "completo"],
    estado: "publicado",
    createdAt: "2024-02-10",
  },
  {
    id: "rec-009",
    nombre: "Tostada de aguacate con huevo",
    descripcion: "Clásico desayuno equilibrado y delicioso",
    tipoComida: "desayuno",
    tiempoPreparacion: 12,
    porciones: 1,
    dificultad: "facil",
    ingredientes: [
      {
        alimentoId: "alim-005",
        nombre: "Huevo entero",
        cantidad: 100,
        calorias: 155,
        proteinas: 13,
        carbohidratos: 1.1,
        grasas: 11,
      },
      {
        alimentoId: "alim-007",
        nombre: "Aguacate",
        cantidad: 80,
        calorias: 128,
        proteinas: 1.6,
        carbohidratos: 7.2,
        grasas: 12,
      },
    ],
    instrucciones: [
      "Tostar el pan",
      "Machacar el aguacate y extender sobre el pan",
      "Cocinar el huevo al gusto (poché, revuelto o frito)",
      "Colocar el huevo sobre el aguacate",
      "Sazonar con sal, pimienta y semillas",
    ],
    caloriasTotal: 283,
    proteinasTotal: 14.6,
    carbohidratosTotal: 8.3,
    grasasTotal: 23,
    caloriasPorcion: 283,
    proteinasPorcion: 14.6,
    carbohidratosPorcion: 8.3,
    grasasPorcion: 23,
    etiquetas: ["vegetariano", "sin_gluten", "rapido"],
    estado: "publicado",
    createdAt: "2024-02-11",
  },
  {
    id: "rec-010",
    nombre: "Bol de quinoa con verduras",
    descripcion: "Comida completa vegana en borrador para revisión",
    tipoComida: "comida",
    tiempoPreparacion: 35,
    porciones: 2,
    dificultad: "media",
    ingredientes: [
      {
        alimentoId: "alim-004",
        nombre: "Brócoli",
        cantidad: 200,
        calorias: 68,
        proteinas: 5.6,
        carbohidratos: 14,
        grasas: 0.8,
      },
      {
        alimentoId: "alim-012",
        nombre: "Espinacas frescas",
        cantidad: 100,
        calorias: 23,
        proteinas: 2.9,
        carbohidratos: 3.6,
        grasas: 0.4,
      },
      {
        alimentoId: "alim-010",
        nombre: "Almendras",
        cantidad: 30,
        calorias: 173.7,
        proteinas: 6.3,
        carbohidratos: 6.6,
        grasas: 14.7,
      },
    ],
    instrucciones: [
      "Cocinar la quinoa según instrucciones",
      "Saltear las verduras",
      "Mezclar todo en un bol",
      "Decorar con almendras",
    ],
    caloriasTotal: 264.7,
    proteinasTotal: 14.8,
    carbohidratosTotal: 24.2,
    grasasTotal: 15.9,
    caloriasPorcion: 132.35,
    proteinasPorcion: 7.4,
    carbohidratosPorcion: 12.1,
    grasasPorcion: 7.95,
    etiquetas: ["vegano", "sin_gluten"],
    estado: "borrador",
    createdAt: "2024-02-12",
  },
];

// ============================================
// OPCIONES PARA FILTROS Y SELECT
// ============================================

export const tiposComida = [
  { value: "desayuno", label: "Desayuno" },
  { value: "almuerzo", label: "Almuerzo" },
  { value: "comida", label: "Comida" },
  { value: "merienda", label: "Merienda" },
  { value: "cena", label: "Cena" },
  { value: "snack", label: "Snack" },
];

export const etiquetasComunes = [
  { value: "vegano", label: "Vegano" },
  { value: "vegetariano", label: "Vegetariano" },
  { value: "sin_gluten", label: "Sin Gluten" },
  { value: "sin_lactosa", label: "Sin Lactosa" },
  { value: "alto_proteina", label: "Alto en Proteína" },
  { value: "bajo_calorias", label: "Bajo en Calorías" },
  { value: "bajo_carbohidrato", label: "Bajo en Carbohidratos" },
  { value: "alto_fibra", label: "Alto en Fibra" },
  { value: "grasas_saludables", label: "Grasas Saludables" },
  { value: "omega3", label: "Rico en Omega-3" },
  { value: "rapido", label: "Rápido" },
  { value: "meal_prep", label: "Meal Prep" },
  { value: "post_entreno", label: "Post Entreno" },
  { value: "pre_entreno", label: "Pre Entreno" },
  { value: "para_llevar", label: "Para Llevar" },
];

export const estadosReceta = [
  { value: "borrador", label: "Borrador" },
  { value: "publicado", label: "Publicado" },
  { value: "archivado", label: "Archivado" },
];
